#nullable enable // autogenerated

using PVZEngine.Tools.Mathematics;
using UnityEngine;

namespace PVZEngine.Tools.Geometry
{
    public struct Cylinder
    {
        public Cylinder(Axis axis, Vector3 center, float length, float radius)
        {
            this.axis = axis;
            this.center = center;
            this.length = length;
            this.radius = radius;
        }
        public Axis axis;
        public Vector3 center;
        public float length;
        public float radius;
    }
}