#nullable enable // autogenerated

using UnityEngine;

namespace PVZEngine.Tools.Geometry
{
    // 凸体接口
    public interface IConvexShape
    {
        Vector3 GetFarthestPointInDirection(Vector3 direction);
        Vector3 GetCenter();
    }
}