#nullable enable // autogenerated

using System.Collections.Generic;

namespace PVZEngine.Collisions.Level
{
    public class ActiveColliderComparer : IComparer<BuiltinCollisionCollider>
    {
        public ActiveColliderComparer()
        {
        }
        public int Compare(BuiltinCollisionCollider c1, BuiltinCollisionCollider c2)
        {
            var ent1 = c1.Entity;
            var ent2 = c2.Entity;
            var typeResult = ent1.Type.CompareTo(ent2.Type);
            if (typeResult != 0)
                return typeResult;
            var id1 = ent1.ID;
            var id2 = ent2.ID;
            var idResult = id1.CompareTo(id2);
            if (idResult != 0)
                return idResult;
            return c1.Name.CompareTo(c2.Name);
        }
    }
}
