#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using System.Linq;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.Tools.Geometry;
using UnityEngine;
using UnityEngine.Pool;

namespace PVZEngine.Collisions.Level
{
    public class BuiltinCollisionSystem : ICollisionSystem
    {
        public BuiltinCollisionSystem(QuadTreeParams treeParams)
        {
            quadTreeParams = treeParams;
            entityPool = new ObjectPool<BuiltinCollisionEntity>(CreateEntityFunc);
        }
        public void Update()
        {
            UpdateTrash();
            Simulate();
        }
        private void Simulate()
        {
            colliderBuffer.Clear();
            foreach (var quadTreePair in quadTrees)
            {
                var quadTree = quadTreePair.Value;
                quadTree.Update();
                quadTree.GetAllTargets(colliderBuffer);
            }

            foreach (var collider1 in colliderBuffer)
            {
                var ent1 = collider1.Entity;
                var ent1Cache = ent1.Cache;
                if (ent1Cache.CollisionInterval > 1 && !ent1.IsTimeInterval(ent1Cache.CollisionInterval))
                    continue;

                if (!ent1.IsCollisionCheckDisabled())
                {
                    int maskHostile = ent1.GetCollisionMaskHostile();
                    int maskFriendly = ent1.GetCollisionMaskFriendly();
                    var maskTotal = maskHostile | maskFriendly;
                    int ent1Faction = ent1Cache.Faction;


                    var sorter = colliderComparer;
                    sorter.SetCollider(collider1);

                    var rect1 = collider1.GetCollisionRect();

                    colliderFilter.SetParameters(collider1, maskHostile, maskFriendly, ent1Faction);

                    collisionBuffer.Clear();
                    FindCollidersRange(maskTotal, rect1, collisionBuffer, 0, colliderFilter);
                    collisionBuffer.Sort(sorter);

                    foreach (var collider2 in collisionBuffer)
                    {
                        collider1.DoCollision(collider2, Vector3.zero);
                    }
                }
                collider1.ExitCollision();
            }
        }
        private void UpdateTrash()
        {
            foreach (var trash in entityTrash)
            {
                entityPool.Release(trash.Value);
            }
            entityTrash.Clear();
        }



        #region 实体
        public void InitEntity(Entity entity)
        {
            var collisionEntity = CreateCollisionEntity();
            collisionEntity.Init(entity);
            entities.Add(entity.ID, collisionEntity);
        }
        public void UpdateEntityDetection(Entity entity)
        {
            var collisionEntity = GetCollisionEntity(entity);
            collisionEntity?.UpdateEntityDetection();
        }
        public void UpdateEntityPosition(Entity entity)
        {
            var collisionEntity = GetCollisionEntity(entity);
            collisionEntity?.UpdateEntityPosition();
        }
        public void UpdateEntitySize(Entity entity)
        {
            var collisionEntity = GetCollisionEntity(entity);
            collisionEntity?.UpdateEntitySize();
        }
        public void DestroyEntity(Entity entity)
        {
            var collisionEntity = GetCollisionEntity(entity);
            if (collisionEntity == null)
                return;
            RemoveCollisionEntity(collisionEntity);
        }
        public void GetCurrentCollisions(Entity entity, List<EntityCollision> collisions)
        {
            var collisionEntity = GetCollisionEntity(entity);
            if (collisionEntity == null)
                return;
            collisionEntity.GetCurrentCollisions(collisions);
        }

        private BuiltinCollisionEntity CreateEntityFunc()
        {
            return new BuiltinCollisionEntity();
        }
        public BuiltinCollisionEntity CreateCollisionEntity()
        {
            var collisionEnt = entityPool.Get();
            collisionEnt.OnEntityColliderEnabled += OnEntityColliderEnabledCallback;
            collisionEnt.OnEntityColliderDisabled += OnEntityColliderDisabledCallback;
            collisionEnt.OnEntityColliderAdd += OnEntityColliderAddCallback;
            collisionEnt.OnEntityColliderRemove += OnEntityColliderRemoveCallback;
            return collisionEnt;
        }
        public BuiltinCollisionEntity? GetCollisionEntity(Entity entity)
        {
            return entities.TryGetValue(entity.ID, out var collisionEntity) ? collisionEntity : null;
        }
        public bool RemoveCollisionEntity(BuiltinCollisionEntity entity)
        {
            var id = entity.ID;
            if (entities.Remove(id))
            {
                entity.ClearColliders();
                entity.OnEntityColliderEnabled -= OnEntityColliderEnabledCallback;
                entity.OnEntityColliderDisabled -= OnEntityColliderDisabledCallback;
                entity.OnEntityColliderAdd -= OnEntityColliderAddCallback;
                entity.OnEntityColliderRemove -= OnEntityColliderRemoveCallback;
                entityTrash.Add(id, entity);
                return true;
            }
            return false;
        }
        #endregion


        #region 碰撞体
        public IEntityCollider? CreateCustomCollider(Entity entity, ColliderConstructor cons)
        {
            var collisionEntity = GetCollisionEntity(entity);
            if (collisionEntity == null)
                return null;
            return collisionEntity.CreateCustomCollider(cons);
        }
        public void AddCollider(Entity entity, IEntityCollider collider)
        {
            if (collider is not BuiltinCollisionCollider entCol)
                return;
            var collisionEntity = GetCollisionEntity(entity);
            if (collisionEntity == null)
                return;
            collisionEntity.AddCollider(entCol);
        }
        public bool RemoveCollider(Entity entity, string name)
        {
            var collisionEntity = GetCollisionEntity(entity);
            if (collisionEntity == null)
                return false;
            return collisionEntity.RemoveCollider(name);
        }
        public BuiltinCollisionCollider? GetCollider(Entity entity, string name)
        {
            var collisionEntity = GetCollisionEntity(entity);
            if (collisionEntity == null)
                return null;
            return collisionEntity.GetCollider(name);
        }
        IEntityCollider? ICollisionSystem.GetCollider(Entity entity, string name) => GetCollider(entity, name);

        #endregion

        #region 检测
        public IEntityCollider[] OverlapBox(Vector3 center, Vector3 size, OverlapParams param)
        {
            var min = center - size * 0.5f;
            var filterRect = new Rect(min.x, min.z, size.x, size.z);
            var bounds = new Bounds(center, size);
            return Overlap(filterRect, param, h => bounds.IntersectsOptimized(h.GetBounds()));
        }
        public void OverlapBoxNonAlloc(Vector3 center, Vector3 size, OverlapParams param, List<IEntityCollider> results)
        {
            var min = center - size * 0.5f;
            var filterRect = new Rect(min.x, min.z, size.x, size.z);
            var bounds = new Bounds(center, size);
            OverlapNonAlloc(filterRect, param, h => bounds.IntersectsOptimized(h.GetBounds()), results);
        }
        public IEntityCollider[] OverlapSphere(Vector3 center, float radius, OverlapParams param)
        {
            var min = center - Vector3.one * radius;
            var filterRect = new Rect(min.x, min.z, radius * 2, radius * 2);
            return Overlap(filterRect, param, h => Geometry.CollideBetweenCubeAndSphere(h.GetBounds(), center, radius));
        }
        public void OverlapSphereNonAlloc(Vector3 center, float radius, OverlapParams param, List<IEntityCollider> results)
        {
            var min = center - Vector3.one * radius;
            var filterRect = new Rect(min.x, min.z, radius * 2, radius * 2);
            OverlapNonAlloc(filterRect, param, h => Geometry.CollideBetweenCubeAndSphere(h.GetBounds(), center, radius), results);
        }
        public IEntityCollider[] OverlapCapsule(Vector3 point0, Vector3 point1, float radius, OverlapParams param)
        {
            var center = (point1 + point0) * 0.5f;
            var min = center - Vector3.one * radius;
            var filterRect = new Rect(min.x, min.z, radius * 2, radius * 2);
            var capsule = new Capsule(point0, point1, radius);
            return Overlap(filterRect, param, h => Geometry.CollideBetweenCubeAndCapsule(capsule, h.GetBounds()));
        }
        public void OverlapCapsuleNonAlloc(Vector3 point0, Vector3 point1, float radius, OverlapParams param, List<IEntityCollider> results)
        {
            var center = (point1 + point0) * 0.5f;
            var min = center - Vector3.one * radius;
            var filterRect = new Rect(min.x, min.z, radius * 2, radius * 2);
            var capsule = new Capsule(point0, point1, radius);
            OverlapNonAlloc(filterRect, param, h => Geometry.CollideBetweenCubeAndCapsule(capsule, h.GetBounds()), results);
        }
        public IEntityCollider[] Overlap(Rect filterRect, OverlapParams param, Predicate<Hitbox> predicate)
        {
            if (predicate == null)
                return Array.Empty<IEntityCollider>();
            var totalMask = param.hostileMask | param.friendlyMask;
            overlapFilter.SetParameters(param, predicate);
            overlapBuffer.Clear();
            FindCollidersRange(totalMask, filterRect, overlapBuffer, 0, overlapFilter);
            return overlapBuffer.ToArray();
        }
        private void OverlapNonAlloc(Rect filterRect, OverlapParams param, Predicate<Hitbox> predicate, List<IEntityCollider> results)
        {
            if (predicate == null)
                return;
            var totalMask = param.hostileMask | param.friendlyMask;
            overlapFilter.SetParameters(param, predicate);
            overlapBuffer.Clear();
            FindCollidersRange(totalMask, filterRect, overlapBuffer, 0, overlapFilter);
            results.AddRange(overlapBuffer);
        }
        #endregion

        #region 四叉树
        public QuadTreeCollider? GetCollisionQuadTree(int flag)
        {
            if (quadTrees.TryGetValue(flag, out var tree))
                return tree;
            return null;
        }
        private void FindCollidersRange(int mask, Rect rect, List<BuiltinCollisionCollider> results, float rewind = 0, IQuadTreeNodeFilter<BuiltinCollisionCollider>? filter = null)
        {
            foreach (var pair in quadTrees)
            {
                var flag = pair.Key;
                if ((flag & mask) == 0)
                    continue;
                var quadTree = pair.Value;
                quadTree.FindTargetsInRect(rect, results, rewind, filter);
            }
        }
        private void InsertColliderToTree(int flag, BuiltinCollisionCollider collider)
        {
            if (!quadTrees.TryGetValue(flag, out var tree))
            {
                tree = CreateQuadTree();
                quadTrees.Add(flag, tree);
            }
            tree.Insert(collider);
        }
        private void RemoveColliderFromTree(int flag, BuiltinCollisionCollider collider)
        {
            if (!quadTrees.TryGetValue(flag, out var tree))
            {
                return;
            }
            tree.Remove(collider);
        }
        private QuadTreeCollider CreateQuadTree()
        {
            return new QuadTreeCollider(quadTreeParams.size, quadTreeParams.maxObjects, quadTreeParams.collapseObjects, quadTreeParams.maxDepth);
        }
        #endregion

        #region 回调
        private void OnEntityColliderEnabledCallback(BuiltinCollisionEntity entity, BuiltinCollisionCollider collider)
        {
            InsertColliderToTree(entity.Entity.TypeCollisionFlag, collider);
        }
        private void OnEntityColliderDisabledCallback(BuiltinCollisionEntity entity, BuiltinCollisionCollider collider)
        {
            RemoveColliderFromTree(collider.Entity.TypeCollisionFlag, collider);
        }
        private void OnEntityColliderAddCallback(BuiltinCollisionEntity entity, BuiltinCollisionCollider collider)
        {
            if (collider.Enabled)
            {
                InsertColliderToTree(entity.Entity.TypeCollisionFlag, collider);
            }
        }
        private void OnEntityColliderRemoveCallback(BuiltinCollisionEntity entity, BuiltinCollisionCollider collider)
        {
            if (collider.Enabled)
            {
                RemoveColliderFromTree(entity.Entity.TypeCollisionFlag, collider);
            }
        }
        #endregion

        public SerializableBuiltinCollisionSystem ToSerializable()
        {
            var seri = new SerializableBuiltinCollisionSystem();
            seri.entities = entities.Select(p => p.Value.ToSerializable()).ToArray();
            seri.entityTrash = entityTrash.Select(p => p.Value.ToSerializable()).ToArray();
            return seri;
        }
        public void LoadFromSerializable(LevelEngine level, ISerializableCollisionSystem seri)
        {
            if (seri.Entities != null)
            {
                foreach (var seriEnt in seri.Entities)
                {
                    if (seriEnt == null)
                        continue;
                    var entity = CreateCollisionEntity();
                    entity.LoadFromSerializable(level, seriEnt);
                    entities.Add(seriEnt.ID, entity);
                }
            }
            if (seri.EntityTrash != null)
            {
                foreach (var seriEnt in seri.EntityTrash)
                {
                    if (seriEnt == null)
                        continue;
                    var entity = CreateCollisionEntity();
                    entity.LoadFromSerializable(level, seriEnt);
                    entityTrash.Add(seriEnt.ID, entity);
                }
            }
            if (seri.Entities != null)
            {
                foreach (var seriEnt in seri.Entities)
                {
                    if (seriEnt == null)
                        continue;
                    var entity = entities[seriEnt.ID];
                    entity.LoadCollisions(level, seriEnt);
                }
            }
            if (seri.EntityTrash != null)
            {
                foreach (var seriEnt in seri.EntityTrash)
                {
                    if (seriEnt == null)
                        continue;
                    var entity = entityTrash[seriEnt.ID];
                    entity.LoadCollisions(level, seriEnt);
                }
            }
        }
        ISerializableCollisionSystem ICollisionSystem.ToSerializable()
        {
            return ToSerializable();
        }


        private List<BuiltinCollisionCollider> colliderBuffer = new List<BuiltinCollisionCollider>();
        private List<BuiltinCollisionCollider> collisionBuffer = new List<BuiltinCollisionCollider>();
        private List<BuiltinCollisionCollider> overlapBuffer = new List<BuiltinCollisionCollider>();
        private ObjectPool<BuiltinCollisionEntity> entityPool;
        private Dictionary<int, QuadTreeCollider> quadTrees = new Dictionary<int, QuadTreeCollider>();
        private QuadTreeParams quadTreeParams;
        private ColliderComparer colliderComparer = new ColliderComparer();
        private QuadTreeNodeFilterCollider colliderFilter = new QuadTreeNodeFilterCollider();
        private QuadTreeNodeFilterOverlapCollider overlapFilter = new QuadTreeNodeFilterOverlapCollider();

        private SortedDictionary<long, BuiltinCollisionEntity> entities = new SortedDictionary<long, BuiltinCollisionEntity>();
        private SortedDictionary<long, BuiltinCollisionEntity> entityTrash = new SortedDictionary<long, BuiltinCollisionEntity>();
    }
    public class SerializableBuiltinCollisionSystem : ISerializableCollisionSystem
    {
        public SerializableBuiltinCollisionSystemEntity?[]? entities;
        public SerializableBuiltinCollisionSystemEntity?[]? entityTrash;
        ISerializableCollisionEntity?[]? ISerializableCollisionSystem.Entities => entities;
        ISerializableCollisionEntity?[]? ISerializableCollisionSystem.EntityTrash => entityTrash;
    }
}
