#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using UnityEngine;

namespace PVZEngine.Collisions.Level
{
    public class ColliderComparer : IComparer<BuiltinCollisionCollider>
    {
        public ColliderComparer(float precision = 1)
        {
            this.precision = precision;
        }
        public void SetCollider(BuiltinCollisionCollider collider)
        {
            this.collider = collider;
            var ent1 = collider.Entity;
            prevPosition = collider.GetPosition() - (ent1.Position - ent1.PreviousPosition);
            collisionTimeCache.Clear();
        }

        public int Compare(BuiltinCollisionCollider c1, BuiltinCollisionCollider c2)
        {
            var collisionTime1 = GetCollisionTime(c1);
            var collisionTime2 = GetCollisionTime(c2);
            var distanceResult = collisionTime1.CompareTo(collisionTime2);
            if (distanceResult != 0)
                return distanceResult;
            var id1 = c1.Entity.ID;
            var id2 = c2.Entity.ID;
            var idResult = id1.CompareTo(id2);
            if (idResult != 0)
                return idResult;
            return c1.Name.CompareTo(c2.Name);
        }
        private float GetCollisionTime(BuiltinCollisionCollider c)
        {
            if (collider == null)
                throw new NullReferenceException($"Collider of a {nameof(ColliderComparer)} is not set before comparing.");
            if (!collisionTimeCache.TryGetValue(c, out var time))
            {
                time = collider.GetCollisionTime(prevPosition, c, precision, out var t) ? t : float.PositiveInfinity;
                collisionTimeCache.Add(c, time);
            }
            return time;
        }
        private float precision = 1;
        private BuiltinCollisionCollider? collider;
        private Vector3 prevPosition;
        private Dictionary<BuiltinCollisionCollider, float> collisionTimeCache = new Dictionary<BuiltinCollisionCollider, float>();
    }
}
