#nullable enable // autogenerated

using PVZEngine.Entities;
using UnityEngine;

namespace PVZEngine.Collisions.Level
{
    public class QuadTreeNodeFilterOverlapBoxCollider : IQuadTreeNodeFilter<BuiltinCollisionCollider>
    {
        public void SetParameters(OverlapParams param, Vector3 center, Vector3 size)
        {
            this.param = param;
            this.center = center;
            this.size = size;
        }

        public bool Validate(BuiltinCollisionCollider collider2)
        {
            var entity = collider2.Entity;
            if (!param.includeIgnored && entity.IsCollisionOverlapDisabled())
                return false;
            if (EntityCollisionHelper.CanCollideFaction(param.hostileMask, param.friendlyMask, param.faction, entity))
            {
                var hitbox = collider2.GetHitbox();
                if (hitbox.IsInBox(center, size))
                {
                    return true;
                }
            }
            return false;
        }
        private OverlapParams param;
        private Vector3 center;
        private Vector3 size;
    }
    public class QuadTreeNodeFilterOverlapSphereCollider : IQuadTreeNodeFilter<BuiltinCollisionCollider>
    {
        public void SetParameters(OverlapParams param, Vector3 center, float radius)
        {
            this.param = param;
            this.center = center;
            this.radius = radius;
        }

        public bool Validate(BuiltinCollisionCollider collider2)
        {
            var entity = collider2.Entity;
            if (!param.includeIgnored && entity.IsCollisionOverlapDisabled())
                return false;
            if (EntityCollisionHelper.CanCollideFaction(param.hostileMask, param.friendlyMask, param.faction, entity))
            {
                var hitbox = collider2.GetHitbox();
                if (hitbox.IsInSphere(center, radius))
                {
                    return true;
                }
            }
            return false;
        }
        private OverlapParams param;
        private Vector3 center;
        private float radius;
    }
    public class QuadTreeNodeFilterOverlapCapsuleCollider : IQuadTreeNodeFilter<BuiltinCollisionCollider>
    {
        public void SetParameters(OverlapParams param, Vector3 point0, Vector3 point1, float radius)
        {
            this.param = param;
            this.point0 = point0;
            this.point1 = point1;
            this.radius = radius;
        }

        public bool Validate(BuiltinCollisionCollider collider2)
        {
            var entity = collider2.Entity;
            if (!param.includeIgnored && entity.IsCollisionOverlapDisabled())
                return false;
            if (EntityCollisionHelper.CanCollideFaction(param.hostileMask, param.friendlyMask, param.faction, entity))
            {
                var hitbox = collider2.GetHitbox();
                if (hitbox.IsInCapsule(point0, point1, radius))
                {
                    return true;
                }
            }
            return false;
        }
        private OverlapParams param;
        private Vector3 point0;
        private Vector3 point1;
        private float radius;
    }
}
