#nullable enable // autogenerated

using PVZEngine.Entities;

namespace PVZEngine.Collisions.Level
{
    public class QuadTreeNodeFilterCollider : IQuadTreeNodeFilter<BuiltinCollisionCollider>
    {
        public void SetParameters(BuiltinCollisionCollider collider, int maskHostile, int maskFriendly, int faction)
        {
            this.collider = collider;
            this.maskFriendly = maskFriendly;
            this.maskHostile = maskHostile;
            this.faction = faction;
        }

        public bool Validate(BuiltinCollisionCollider collider2)
        {
            if (collider == null || collider == collider2)
                return false;
            var ent1 = collider.Entity;
            var ent2 = collider2.Entity;
            if (ent1 == ent2)
                return false;
            if (ent2.IsCollisionCheckDisabled())
                return false;
            if (!EntityCollisionHelper.CanCollideFaction(maskHostile, maskFriendly, faction, ent2))
                return false;
            return true;
        }
        private BuiltinCollisionCollider? collider;
        private int maskFriendly;
        private int maskHostile;
        private int faction;
    }
}
