#nullable enable // autogenerated

using System;
using PVZEngine.Entities;

namespace PVZEngine.Collisions.Level
{
    public class QuadTreeNodeFilterOverlapCollider : IQuadTreeNodeFilter<BuiltinCollisionCollider>
    {
        public void SetParameters(OverlapParams param, Predicate<Hitbox>? hitboxPredicate)
        {
            this.param = param;
            this.hitboxPredicate = hitboxPredicate;
        }

        public bool Validate(BuiltinCollisionCollider collider2)
        {
            var entity = collider2.Entity;
            if (!param.includeIgnored && entity.IsCollisionOverlapDisabled())
                return false;
            if (EntityCollisionHelper.CanCollideFaction(param.hostileMask, param.friendlyMask, param.faction, entity))
            {
                var hitbox = collider2.GetHitbox();
                if (hitboxPredicate == null || hitboxPredicate(hitbox))
                {
                    return true;
                }
            }
            return false;
        }
        private OverlapParams param;
        private Predicate<Hitbox>? hitboxPredicate;
    }
}
