#nullable enable // autogenerated

using System.Collections.Generic;
using UnityEngine;

namespace PVZEngine.Damages
{
    public class DamageCalculator
    {
        public DamageCalculator(float amount)
        {
            BaseAmount = amount;
        }
        public void AddOperation(IDamageOperation operation)
        {
            operations.Add(operation);
        }
        public void ClearOperations()
        {
            operations.Clear();
        }
        public float GetFinalAmount()
        {
            return GetFinalAmount(BaseAmount);
        }
        public float GetFinalAmount(float amount)
        {
            foreach (var operation in operations)
            {
                amount = operation.Operate(amount);
            }
            return amount;
        }
        public float GetOverflowAmount(float targetHP, float actualAmount)
        {
            var absorbedAmount = Mathf.Min(targetHP, actualAmount);
            var amount = actualAmount - absorbedAmount;
            if (amount <= 0)
                return 0;
            for (int i = operations.Count - 1; i >= 0; i--)
            {
                var operation = operations[i];
                amount = operation.OperateInverse(amount);
            }
            return amount;
        }
        public float BaseAmount { get; set; }
        private List<IDamageOperation> operations = new List<IDamageOperation>();
    }
}
