#nullable enable // autogenerated

namespace PVZEngine.Damages
{
    public abstract class DamageOperationBinary : IDamageOperation
    {
        public DamageOperationBinary(float operand)
        {
            Operand = operand;
        }
        public abstract float Operate(float value);
        public abstract float OperateInverse(float value);
        public float Operand { get; }
    }
}
