#nullable enable // autogenerated

namespace PVZEngine.Damages
{
    public class DamageOperationPlus : DamageOperationBinary
    {
        public DamageOperationPlus(float operand) : base(operand) { }
        public override float Operate(float value)
        {
            return value + Operand;
        }

        public override float OperateInverse(float value)
        {
            return value - Operand;
        }
    }
}
