#nullable enable // autogenerated

namespace PVZEngine.Damages
{
    public class DamageOperationMultiply : DamageOperationBinary
    {
        public DamageOperationMultiply(float operand) : base(operand) { }
        public override float Operate(float value)
        {
            return value * Operand;
        }

        public override float OperateInverse(float value)
        {
            if (Operand == 0)
            {
                return float.PositiveInfinity;
            }
            return value / Operand;
        }
    }
}
