#nullable enable // autogenerated

using PVZEngine.Modifiers;

namespace PVZEngine.Buffs
{
    public partial class Buff
    {
        public int GetModifierCount()
        {
            return Definition.GetModifierCount();
        }
        public PropertyModifier GetModifierAt(int index)
        {
            return Definition.GetModifierAt(index);
        }
        T? IModifierSource.GetProperty<T>(PropertyKey<T> name) where T : default => GetProperty<T>(name);
    }
}
