#nullable enable // autogenerated

using System;
using MongoDB.Bson.Serialization.Attributes;
using PVZEngine.Buffs;
using PVZEngine.Level;

namespace PVZEngine.Entities
{
    [Serializable]
    public class BuffSourceReference : ILevelSourceReference
    {
        public BuffSourceReference(IBuffReference reference, NamespaceID defID)
        {
            this.reference = reference;
            this.definitionID = defID;
        }
        public BuffSourceReference(IBuffTarget target, Buff buff)
        {
            this.reference = target.GetBuffReference(buff);
            this.definitionID = buff.Definition.GetID();
        }
        public BuffSourceReference Clone()
        {
            return new BuffSourceReference(Reference, DefinitionID);
        }
        public Buff? GetBuff(LevelEngine level)
        {
            return reference.GetBuff(level);
        }
        public override bool Equals(object obj)
        {
            if (obj is BuffSourceReference buffRef)
            {
                return reference.Equals(buffRef.reference);
            }
            return base.Equals(obj);
        }
        public override int GetHashCode()
        {
            return Reference.GetHashCode();
        }
        public static bool operator ==(BuffSourceReference lhs, BuffSourceReference rhs)
        {
            if (lhs is null)
                return rhs is null;
            return lhs.Equals(rhs);
        }
        public static bool operator !=(BuffSourceReference lhs, BuffSourceReference rhs)
        {
            return !(lhs == rhs);
        }
        ILevelSourceReference ILevelSourceReference.CloneReference()
        {
            return Clone();
        }
        ILevelSourceTarget? ILevelSourceReference.GetTarget(LevelEngine level)
        {
            return GetBuff(level);
        }
        ILevelSourceReference? ILevelSourceReference.GetParent() => null;
        [BsonIgnore]
        public NamespaceID DefinitionID => definitionID;
        [BsonIgnore]
        public IBuffReference Reference => reference;
        [BsonElement]
        private NamespaceID definitionID;
        [BsonElement]
        private IBuffReference reference;
    }
}