#nullable enable // autogenerated

using System;
using System.Collections;
using System.Collections.Generic;
using PVZEngine.Level;
using PVZEngine.Modifiers;
using PVZEngine.Tools;

namespace PVZEngine.Buffs
{
    public class BuffList : IEnumerable<Buff>, IBuffList
    {
        public BuffList()
        {
            modifierLibrary = new ModifierLibrary();
            modifierLibrary.OnModifiedPropertyNeedsUpdate += OnModifiedPropertyNeedsUpdateCallback;
        }

        #region 增益操作
        public long AllocBuffID()
        {
            return currentBuffID++;
        }
        public bool AddBuff(Buff buff, IBuffTarget target)
        {
            if (AddBuffImplement(buff))
            {
                buff.AddToTarget(target);
                return true;
            }
            return false;
        }

        #region 移除
        public bool RemoveBuff(Buff buff)
        {
            return RemoveBuffImplement(buff);
        }
        #endregion

        #region 移除多个
        public int RemoveBuffs(BuffDefinition buffDef)
        {
            if (buffDef == null)
                return 0;

            int count = 0;
            for (int i = buffs.Count - 1; i >= 0; i--)
            {
                var buff = buffs[i];
                if (buff.Definition != buffDef)
                    continue;
                count += RemoveBuffImplement(buff) ? 1 : 0;
            }
            return count;
        }
        public int RemoveBuffs(IEnumerable<Buff> buffs)
        {
            if (buffs == null)
                return 0;

            int count = 0;
            foreach (var buff in buffs)
            {
                count += RemoveBuffImplement(buff) ? 1 : 0;
            }
            return count;
        }
        public int RemoveBuffs(NamespaceID id)
        {
            if (!NamespaceID.IsValid(id))
                return 0;

            int count = 0;
            for (int i = buffs.Count - 1; i >= 0; i--)
            {
                var buff = buffs[i];
                if (buff.Definition.GetID() != id)
                    continue;
                count += RemoveBuffImplement(buff) ? 1 : 0;
            }
            return count;
        }
        public int RemoveBuffs<T>() where T : BuffDefinition
        {
            int count = 0;
            for (int i = buffs.Count - 1; i >= 0; i--)
            {
                var buff = buffs[i];
                if (buff.Definition is not T)
                    continue;
                count += RemoveBuffImplement(buff) ? 1 : 0;
            }
            return count;
        }
        #endregion

        #region 包含
        public bool HasBuff<T>() where T : BuffDefinition
        {
            foreach (var buff in buffs)
            {
                if (buff.Definition is T)
                    return true;
            }
            return false;
        }
        public bool HasBuff(NamespaceID id)
        {
            foreach (var buff in buffs)
            {
                if (buff.Definition.GetID() == id)
                    return true;
            }
            return false;
        }
        public bool HasBuff(BuffDefinition buffDef)
        {
            foreach (var buff in buffs)
            {
                if (buff.Definition == buffDef)
                    return true;
            }
            return false;
        }
        public bool HasBuff(Buff buff)
        {
            return buffs.Contains(buff);
        }
        #endregion

        #region 获取单个
        public Buff? GetBuff(long id)
        {
            foreach (var buff in buffs)
            {
                if (buff.ID == id)
                    return buff;
            }
            return null;
        }
        public Buff? GetFirstBuff<T>() where T : BuffDefinition
        {
            foreach (var buff in buffs)
            {
                if (buff.Definition is T)
                {
                    return buff;
                }
            }
            return null;
        }
        public Buff? GetFirstBuff(BuffDefinition definition)
        {
            foreach (var buff in buffs)
            {
                if (buff.Definition == definition)
                {
                    return buff;
                }
            }
            return null;
        }
        public Buff? GetFirstBuff(NamespaceID id)
        {
            foreach (var buff in buffs)
            {
                if (buff.Definition.GetID() == id)
                {
                    return buff;
                }
            }
            return null;
        }
        #endregion

        #region 获取多个
        public Buff[] GetBuffs<T>() where T : BuffDefinition
        {
            var list = new List<Buff>();
            GetBuffsNonAlloc<T>(list);
            return list.ToArray();
        }
        public Buff[] GetBuffs(BuffDefinition definition)
        {
            var list = new List<Buff>();
            GetBuffsNonAlloc(definition, list);
            return list.ToArray();
        }
        public Buff[] GetBuffs(NamespaceID id)
        {
            var list = new List<Buff>();
            GetBuffsNonAlloc(id, list);
            return list.ToArray();
        }
        public void GetBuffsNonAlloc<T>(List<Buff> results) where T : BuffDefinition
        {
            foreach (var buff in buffs)
            {
                if (buff.Definition is T)
                {
                    results.Add(buff);
                }
            }
        }
        public void GetBuffsNonAlloc(BuffDefinition definition, List<Buff> results)
        {
            foreach (var buff in buffs)
            {
                if (buff.Definition == definition)
                {
                    results.Add(buff);
                }
            }
        }
        public void GetBuffsNonAlloc(NamespaceID id, List<Buff> results)
        {
            foreach (var buff in buffs)
            {
                if (buff.Definition.GetID() == id)
                {
                    results.Add(buff);
                }
            }
        }
        #endregion

        #region 获取数量
        public int GetBuffCount<T>() where T : BuffDefinition
        {
            int count = 0;
            foreach (var buff in buffs)
            {
                if (buff.Definition is T)
                    count++;
            }
            return count;
        }
        public int GetBuffCount(BuffDefinition definition)
        {
            int count = 0;
            foreach (var buff in buffs)
            {
                if (buff.Definition == definition)
                    count++;
            }
            return count;
        }
        public int GetBuffCount(NamespaceID id)
        {
            int count = 0;
            foreach (var buff in buffs)
            {
                if (buff.Definition.GetID() == id)
                    count++;
            }
            return count;
        }
        #endregion

        #region 获取全部
        public void GetAllBuffs(List<Buff> results)
        {
            results.AddRange(buffs);
        }
        #endregion

        public void Update()
        {
            updateBuffer.Clear();
            GetAllBuffs(updateBuffer);
            foreach (var buff in updateBuffer)
            {
                buff.Update();
            }
        }
        private bool AddBuffImplement(Buff buff)
        {
            if (buff == null)
                return false;

            using var lastInsertionsBuffer = ListPool<ModelInsertion>.Rent();
            var lastInsertions = lastInsertionsBuffer.Value;
            GetModelInsertions(lastInsertions);

            buffs.Add(buff);
            AddModifierCaches(buff);
            OnBuffAdded?.Invoke(buff);
            buff.OnPropertyChanged += OnBuffPropertyChangedCallback;

            var insertions = buff.GetModelInsertions();
            foreach (var insertion in insertions)
            {
                var key = insertion.key;
                ModelInsertion? lastInsertion = null;
                foreach (var ins in lastInsertions)
                {
                    if (ins.key == key)
                    {
                        lastInsertion = ins;
                        break;
                    }
                }
                if (lastInsertion != null)
                    continue;
                OnModelInsertionAdded?.Invoke(insertion);
            }
            return true;
        }
        private bool RemoveBuffImplement(Buff buff)
        {
            if (buff == null)
                return false;
            if (buffs.Remove(buff))
            {
                buff.RemoveFromTarget();
                RemoveModifierCaches(buff);
                OnBuffRemoved?.Invoke(buff);
                buff.OnPropertyChanged -= OnBuffPropertyChangedCallback;

                using var buffInsertionsItem = ListPool<ModelInsertion>.Rent();
                var buffInsertions = buffInsertionsItem.Value;
                using var currentInsertionsItem = ListPool<ModelInsertion>.Rent();
                var currentInsertions = currentInsertionsItem.Value;
                buff.GetModelInsertionsNonAlloc(buffInsertions);
                GetModelInsertions(currentInsertions);
                foreach (var insertion in buffInsertions)
                {
                    var key = insertion.key;
                    ModelInsertion? currentInsertion = null;
                    foreach (var ins in currentInsertions)
                    {
                        if (ins.key == key)
                        {
                            currentInsertion = ins;
                            break;
                        }
                    }
                    if (currentInsertion != null)
                        continue;
                    OnModelInsertionRemoved?.Invoke(insertion);
                }
                return true;
            }
            return false;
        }
        #endregion

        #region 修改器
        public IEnumerable<IPropertyKey> GetModifiedProperties()
        {
            return modifierLibrary.GetModifyPropertyKeys();
        }
        public void GetModifierItemsForProperty(IPropertyKey name, List<ModifierSourceItem> results)
        {
            modifierLibrary.GetModifierItemsForProperty(name, results);
        }
        private void AddModifierCaches(Buff buff)
        {
            int modifierCount = buff.GetModifierCount();
            for (int i = 0; i < modifierCount; i++)
            {
                var modifier = buff.GetModifierAt(i);
                modifierLibrary.AddModifierCache(new ModifierSourceItem(buff, modifier));
            }
        }
        private void RemoveModifierCaches(Buff buff)
        {
            int modifierCount = buff.GetModifierCount();
            for (int i = 0; i < modifierCount; i++)
            {
                var modifier = buff.GetModifierAt(i);
                modifierLibrary.RemoveModifierCache(new ModifierSourceItem(buff, modifier));
            }
        }
        private void ReevaluateModifierCaches()
        {
            modifierLibrary.ClearModifierCaches();
            foreach (var buff in buffs)
            {
                AddModifierCaches(buff);
            }
        }
        #endregion

        #region 插入模型
        public void GetModelInsertions(List<ModelInsertion> results)
        {
            foreach (var buff in buffs)
            {
                buff.GetModelInsertionsNonAlloc(results);
            }
        }
        #endregion

        #region 序列化
        public SerializableBuffList ToSerializable()
        {
            return new SerializableBuffList()
            {
                buffs = buffs.ConvertAll(b => b.ToSerializable()),
                currentBuffID = currentBuffID,
            };
        }
        public void InitFromSerializable(SerializableBuffList? serializable, LevelEngine level, IBuffTarget target)
        {
            if (serializable == null)
                return;

            buffs.Clear();
            if (serializable.buffs != null)
            {
                foreach (var seriBuff in serializable.buffs)
                {
                    var buff = Buff.CreateFromSerializable(seriBuff, level, target);
                    if (buff == null)
                        continue;
                    buff.OnPropertyChanged += OnBuffPropertyChangedCallback;
                    buffs.Add(buff);
                }
            }
            currentBuffID = serializable.currentBuffID;
            ReevaluateModifierCaches();
        }
        public void LoadFromSerializable(SerializableBuffList serializable)
        {
            if (serializable.buffs != null)
            {
                foreach (var buff in buffs)
                {
                    if (buff == null)
                        continue;
                    SerializableBuff? seriBuff = null;
                    foreach (var sb in serializable.buffs)
                    {
                        if (sb.id == buff.ID)
                        {
                            seriBuff = sb;
                            break;
                        }
                    }
                    if (seriBuff == null)
                        continue;
                    buff.LoadFromSerializable(seriBuff);
                }
            }
        }
        #endregion

        #region 事件回调
        private void OnBuffPropertyChangedCallback(Buff buff, IPropertyKey key)
        {
            modifierLibrary.CallPropertyChanged(buff, key);
        }
        void OnModifiedPropertyNeedsUpdateCallback(IPropertyKey name)
        {
            OnModifiedPropertyNeedsUpdate?.Invoke(name);
        }
        #endregion

        #region 接口实现
        void IModifierProvider.GetModifiersForProperty(IPropertyKey name, List<ModifierSourceItem> results)
        {
            GetModifierItemsForProperty(name, results);
        }

        IEnumerator<Buff> IEnumerable<Buff>.GetEnumerator()
        {
            return buffs.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return buffs.GetEnumerator();
        }
        #endregion

        #region 事件
        public event Action<Buff>? OnBuffAdded;
        public event Action<Buff>? OnBuffRemoved;
        public event Action<ModelInsertion>? OnModelInsertionAdded;
        public event Action<ModelInsertion>? OnModelInsertionRemoved;
        public event Action<IPropertyKey>? OnModifiedPropertyNeedsUpdate;
        #endregion

        #region 属性
        private long currentBuffID = 1;
        private List<Buff> updateBuffer = new List<Buff>();
        private List<Buff> buffs = new List<Buff>();
        private ModifierLibrary modifierLibrary;
        #endregion
    }
    public class MultipleValueModifierException : Exception
    {
        public MultipleValueModifierException(string message) : base(message)
        {
        }

        public MultipleValueModifierException() : base()
        {
        }

        public MultipleValueModifierException(string message, Exception innerException) : base(message, innerException)
        {
        }
    }
    public struct PropertyCalculateResult
    {
        public string name;
        public object value;
    }
}
