#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Auras;
using PVZEngine.Definitions;
using PVZEngine.Modifiers;

namespace PVZEngine.Buffs
{
    public abstract class BuffDefinition : Definition
    {
        public BuffDefinition(string nsp, string name) : base(nsp, name)
        {
        }
        public int GetModifierCount()
        {
            return modifiers.Count;
        }
        public PropertyModifier GetModifierAt(int index)
        {
            return modifiers[index];
        }
        public ModelInsertion[] GetModelInsertions()
        {
            return modelInsertions.ToArray();
        }
        public void GetModelInsertionsNonAlloc(List<ModelInsertion> results)
        {
            results.AddRange(modelInsertions);
        }
        public AuraEffectDefinition[] GetAuras()
        {
            return auraDefinitions.ToArray();
        }
        public virtual void OnCreate(Buff buff) { }
        public virtual void PostAdd(Buff buff) { }
        public virtual void PostRemove(Buff buff) { }
        public virtual void PostUpdate(Buff buff) { }
        protected void AddModifier(PropertyModifier modifier)
        {
            modifiers.Add(modifier);
        }
        protected void AddModelInsertion(string anchorName, NamespaceID key, NamespaceID modelID)
        {
            modelInsertions.Add(new ModelInsertion(anchorName, key, modelID));
        }
        protected void AddAura(AuraEffectDefinition aura)
        {
            auraDefinitions.Add(aura);
        }
        public sealed override string GetDefinitionType() => EngineDefinitionTypes.BUFF;
        private List<PropertyModifier> modifiers = new List<PropertyModifier>();
        private List<AuraEffectDefinition> auraDefinitions = new List<AuraEffectDefinition>();
        private List<ModelInsertion> modelInsertions = new List<ModelInsertion>();
    }
}
