#nullable enable // autogenerated

using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    public interface IBuffTarget : ILevelObject
    {
        IBuffList Buffs { get; }
        IBuffReference GetBuffReference(Buff buff);
    }
}
