#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using PVZEngine.Buffs;
using PVZEngine.Tools;

namespace PVZEngine.Modifiers
{
    public static class PropertyCalculator
    {
        public static object? CalculateProperty(this IList<ModifierSourceItem> modifiers, object? value)
        {
            if (modifiers == null || modifiers.Count == 0)
                return value;

            using var calculatorsItem = HashSetPool<ModifierCalculator>.Rent();
            var calculators = calculatorsItem.Value;

            foreach (var modifierItem in modifiers)
            {
                var calc = modifierItem.modifier.GetCalculator();
                if (calc == null)
                    continue;
                calculators.Add(calc);
            }
            ModifierCalculator? calculator = null;
            foreach (var calc in calculators)
            {
                if (calculator != null)
                    throw new MultipleValueModifierException($"Modifiers of property has multiple different calculators: {string.Join(',', calculators)}");
                calculator = calc;
            }
            if (calculator == null)
                throw new NullReferenceException($"Calculator for property does not exists.");
            return calculator.Calculate(value, modifiers);
        }
        public static T? CalculateProperty<T>(this IList<ModifierSourceItem> modifiers, T? value)
        {
            if (modifiers == null || modifiers.Count == 0)
                return value;

            using var calculatorsItem = HashSetPool<ModifierCalculator>.Rent();
            var calculators = calculatorsItem.Value;

            foreach (var modifierItem in modifiers)
            {
                var calc = modifierItem.modifier.GetCalculator();
                if (calc == null)
                    continue;
                calculators.Add(calc);
            }
            ModifierCalculator<T>? calculator = null;
            foreach (var c in calculators)
            {
                if (c is not ModifierCalculator<T> calc)
                    continue;
                if (calculator != null)
                    throw new MultipleValueModifierException($"Modifiers of property has multiple different calculators: {string.Join(',', calculators)}");
                calculator = calc;
            }
            if (calculator == null)
                throw new NullReferenceException($"Calculator for property does not exists.");
            return calculator.CalculateGeneric(value, modifiers);
        }
    }
}
