#nullable enable // autogenerated

using System.Collections.Concurrent;

namespace PVZEngine.Callbacks
{
    public class CallbackSystem : ICallbackRunner
    {
        public void RunCallback<TArgs>(CallbackType<TArgs> callbackType, TArgs args)
        {
            RunCallbackWithResult<TArgs, object>(callbackType, args, null);
        }
        public TResult? RunCallbackWithResult<TArgs, TResult>(CallbackType<TArgs> callbackType, TArgs args, TResult? result)
        {
            if (handlers.TryGetValue(callbackType, out var handler))
            {
                var callbackHandler = (CallbackHandler<TArgs>)handler;
                using var callbackResultItem = CallbackResult.Rent(result);
                var callbackResult = callbackResultItem.Value;
                callbackHandler.Execute(args, callbackResult);
                result = callbackResult.GetValue<TResult>();
            }
            return result;
        }
        public void RunCallbackFiltered<TArgs>(CallbackType<TArgs> callbackType, TArgs args, object? filter)
        {
            RunCallbackWithResultFiltered<TArgs, object>(callbackType, args, null, filter);
        }
        public TResult? RunCallbackWithResultFiltered<TArgs, TResult>(CallbackType<TArgs> callbackType, TArgs args, TResult? result, object? filter)
        {
            if (handlers.TryGetValue(callbackType, out var handler))
            {
                var callbackHandler = (CallbackHandler<TArgs>)handler;
                using var callbackResultItem = CallbackResult.Rent(result);
                var callbackResult = callbackResultItem.Value;
                callbackHandler.ExecuteFiltered(args, filter, callbackResult);
                result = callbackResult.GetValue<TResult>();
            }
            return result;
        }

        public void AddCallback(ITrigger trigger)
        {
            var handler = handlers.GetOrAdd(trigger.Type, type => type.CreateHandler());
            handler.AddTrigger(trigger);
        }
        public bool RemoveCallback(ITrigger trigger)
        {
            if (handlers.TryGetValue(trigger.Type, out var handler))
            {
                var callbackHandler = handler;
                return callbackHandler.RemoveTrigger(trigger);
            }
            return false;
        }

        private readonly ConcurrentDictionary<ICallbackType, ICallbackHandler> handlers = new ConcurrentDictionary<ICallbackType, ICallbackHandler>();
    }
}
