#nullable enable // autogenerated

namespace PVZEngine.Callbacks
{
    public interface ICallbackType
    {
        internal ICallbackHandler CreateHandler();
    }
    public class CallbackType<TArgs, TResult> : ICallbackType
    {
        public CallbackType() { }
        ICallbackHandler ICallbackType.CreateHandler() => new CallbackHandler<TArgs, TResult>();
    }
    public sealed class CallbackType<TArgs> : CallbackType<TArgs, object>
    {
    }
}
