#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Tools;
using UnityEngine.Pool;

namespace PVZEngine.Callbacks
{
    public abstract class CallbackResultBase
    {
        public void Break() => IsBreakRequested = true;
        public bool IsBreakRequested { get; protected set; }

    }
    public class CallbackResult<T> : CallbackResultBase
    {
        private CallbackResult()
        {
        }
        public void SetValue(T? value)
        {
            this.value = value;
        }
        public void SetFinalValue(T? value)
        {
            SetValue(value);
            Break();
        }
        public T? GetValue()
        {
            return value;
        }

        public static PoolItem<CallbackResult<T>> Rent(T? value)
        {
            var item = new PoolItem<CallbackResult<T>>(pool);
            item.Value.value = value;
            return item;
        }
        private static CallbackResult<T> CreateFunc() => new CallbackResult<T>();
        private static void GetFunc(CallbackResult<T> item) { }
        private static void ReleaseFunc(CallbackResult<T> item)
        {
            item.IsBreakRequested = false;
            item.value = default;
        }
        private T? value;

        private static readonly ObjectPool<CallbackResult<T>> pool = new ObjectPool<CallbackResult<T>>(CreateFunc, GetFunc, ReleaseFunc);
    }
    public class CallbackResultVoid : CallbackResultBase
    {
        public static PoolItem<CallbackResultVoid> Rent()
        {
            return new PoolItem<CallbackResultVoid>(pool);
        }
        private static CallbackResultVoid CreateFunc() => new CallbackResultVoid();
        private static void GetFunc(CallbackResultVoid item) { }
        private static void ReleaseFunc(CallbackResultVoid item)
        {
            item.IsBreakRequested = false;
        }
        private static readonly ObjectPool<CallbackResultVoid> pool = new ObjectPool<CallbackResultVoid>(CreateFunc, GetFunc, ReleaseFunc);
    }
}
