#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Tools;
using UnityEngine.Pool;

namespace PVZEngine.Callbacks
{
    public class CallbackResult
    {
        private CallbackResult()
        {
        }
        public void SetValue(object? value)
        {
            this.value = value;
        }
        public void SetFinalValue(object? value)
        {
            SetValue(value);
            Break();
        }
        public T? GetValue<T>()
        {
            if (value.TryToGeneric<T>(out var v))
                return v;
            return default;
        }
        public void Break() => IsBreakRequested = true;

        public static PoolItem<CallbackResult> Rent(object? value)
        {
            var item = new PoolItem<CallbackResult>(pool);
            item.Value.value = value;
            return item;
        }
        private static CallbackResult CreateFunc() => new CallbackResult();
        private static void GetFunc(CallbackResult item) { }
        private static void ReleaseFunc(CallbackResult item)
        {
            item.IsBreakRequested = false;
            item.value = null;
        }
        public bool IsBreakRequested { get; private set; }
        private object? value;

        private static readonly ObjectPool<CallbackResult> pool = new ObjectPool<CallbackResult>(CreateFunc, GetFunc, ReleaseFunc);
    }
}
