#nullable enable // autogenerated

using System;

namespace PVZEngine.Callbacks
{
    public interface ICallbackType
    {
        internal ICallbackHandler CreateHandler();
    }
    public sealed class CallbackType<TArgs> : ICallbackType
    {
        public CallbackType() { }
        ICallbackHandler ICallbackType.CreateHandler() => new CallbackHandler<TArgs>();
    }
    public class CallbackType<TArgs, TResult> : ICallbackType
    {
        public CallbackType() { }
        ICallbackHandler ICallbackType.CreateHandler() => new CallbackHandler<TArgs, TResult>();
    }
    public sealed class CallbackTypeFiltered<TArgs, TFilter> : ICallbackType
    {
        public CallbackTypeFiltered() { }
        ICallbackHandler ICallbackType.CreateHandler() => new CallbackHandlerFiltered<TArgs, TFilter>();
    }
    public class CallbackTypeFiltered<TArgs, TResult, TFilter> : ICallbackType
    {
        public CallbackTypeFiltered() { }
        ICallbackHandler ICallbackType.CreateHandler() => new CallbackHandlerFiltered<TArgs, TResult, TFilter>();
    }
}
