#nullable enable // autogenerated

using System.Collections.Generic;

namespace PVZEngine.Callbacks
{
    internal interface ICallbackHandler
    {
        void AddTrigger(ITrigger trigger);
        bool RemoveTrigger(ITrigger trigger);
    }
    internal abstract class CallbackHandlerBase<TTrigger> : ICallbackHandler where TTrigger : ITrigger
    {
        public void AddTrigger(TTrigger trigger)
        {
            lock (syncLock)
            {
                int index = triggers.BinarySearch(trigger, new TriggerPriorityComparer<TTrigger>());
                if (index < 0)
                    index = ~index;
                triggers.Insert(index, trigger);
                triggersSnapshot = null;
            }
        }
        public bool RemoveTrigger(TTrigger trigger)
        {
            lock (syncLock)
            {
                if (triggers.Remove(trigger))
                {
                    triggersSnapshot = null;
                    return true;
                }
                return false;
            }
        }
        void ICallbackHandler.AddTrigger(ITrigger trigger)
        {
            if (trigger is TTrigger t)
            {
                AddTrigger(t);
            }
        }
        bool ICallbackHandler.RemoveTrigger(ITrigger trigger)
        {
            if (trigger is TTrigger t)
            {
                return RemoveTrigger(t);
            }
            return false;
        }
        protected TTrigger[] GetTriggersSnapshot()
        {
            if (triggersSnapshot != null)
                return triggersSnapshot;

            lock (syncLock)
            {
                return triggersSnapshot ??= triggers.ToArray();
            }
        }

        protected readonly object syncLock = new object();
        protected List<TTrigger> triggers = new List<TTrigger>();
        protected volatile TTrigger[]? triggersSnapshot;
    }
    internal class CallbackHandler<TArgs> : CallbackHandlerBase<Trigger<TArgs>>
    {
        public void Execute(TArgs args, CallbackResultVoid result)
        {
            var currentTriggers = GetTriggersSnapshot();
            foreach (var trigger in currentTriggers)
            {
                trigger.Action(args, result);
                if (result.IsBreakRequested)
                    break;
            }
        }
    }
    internal class CallbackHandler<TArgs, TResult> : CallbackHandlerBase<Trigger<TArgs, TResult>>
    {
        public void Execute(TArgs args, CallbackResult<TResult> result)
        {
            var currentTriggers = GetTriggersSnapshot();
            foreach (var trigger in currentTriggers)
            {
                trigger.Action(args, result);
                if (result.IsBreakRequested)
                    break;
            }
        }
    }
    internal abstract class CallbackHandlerFilteredBase<TTrigger, TFilter> : CallbackHandlerBase<TTrigger>
        where TTrigger : ITriggerFiltered<TFilter>
    {
        protected bool IsFilterMatched(TTrigger trigger, TFilter? callbackFilter)
        {
            if (!trigger.UseFilter)
                return true;
            var triggerFilter = trigger.Filter;
            if (!isValueType)
            {
                if (triggerFilter is null || callbackFilter is null)
                    return true;
                return _comparer.Equals(triggerFilter, callbackFilter);
            }
            return _comparer.Equals(triggerFilter!, callbackFilter!);
        }
        private static readonly bool isValueType = typeof(TFilter).IsValueType;
        private static readonly EqualityComparer<TFilter> _comparer = EqualityComparer<TFilter>.Default;
    }
    internal class CallbackHandlerFiltered<TArgs, TFilter> : CallbackHandlerFilteredBase<TriggerFiltered<TArgs, TFilter>, TFilter>
    {
        public void Execute(TArgs args, TFilter? filter, CallbackResultVoid result)
        {
            var currentTriggers = GetTriggersSnapshot();
            foreach (var trigger in currentTriggers)
            {
                if (!IsFilterMatched(trigger, filter))
                    continue;

                trigger.Action(args, result);
                if (result.IsBreakRequested)
                    break;
            }
        }
    }
    internal class CallbackHandlerFiltered<TArgs, TResult, TFilter> : CallbackHandlerFilteredBase<TriggerFiltered<TArgs, TResult, TFilter>, TFilter>
    {
        public void Execute(TArgs args, TFilter? filter, CallbackResult<TResult> result)
        {
            var currentTriggers = GetTriggersSnapshot();
            foreach (var trigger in currentTriggers)
            {
                if (!IsFilterMatched(trigger, filter))
                    continue;

                trigger.Action(args, result);
                if (result.IsBreakRequested)
                    break;
            }
        }
    }
    internal class TriggerPriorityComparer<T> : IComparer<T> where T : ITrigger
    {
        public int Compare(T x, T y)
            => x.Priority.CompareTo(y.Priority);
    }
}
