#nullable enable // autogenerated

using System.Collections.Concurrent;

namespace PVZEngine.Callbacks
{
    public class CallbackSystem : ICallbackRunner
    {
        public void RunCallback<TArgs>(CallbackType<TArgs> callbackType, TArgs args)
        {
            if (handlers.TryGetValue(callbackType, out var handler))
            {
                var callbackHandler = (CallbackHandler<TArgs>)handler;
                using var callbackResultItem = CallbackResultVoid.Rent();
                var callbackResult = callbackResultItem.Value;
                callbackHandler.Execute(args, callbackResult);
            }
        }
        public TResult? RunCallbackWithResult<TArgs, TResult>(CallbackType<TArgs, TResult> callbackType, TArgs args, TResult? result)
        {
            if (handlers.TryGetValue(callbackType, out var handler))
            {
                var callbackHandler = (CallbackHandler<TArgs, TResult>)handler;
                using var callbackResultItem = CallbackResult<TResult>.Rent(result);
                var callbackResult = callbackResultItem.Value;
                callbackHandler.Execute(args, callbackResult);
                result = callbackResult.GetValue();
            }
            return result;
        }
        public void RunCallbackFiltered<TArgs, TFilter>(CallbackTypeFiltered<TArgs, TFilter> callbackType, TArgs args, TFilter? filter)
        {
            if (handlers.TryGetValue(callbackType, out var handler))
            {
                var callbackHandler = (CallbackHandlerFiltered<TArgs, TFilter>)handler;
                using var callbackResultItem = CallbackResultVoid.Rent();
                var callbackResult = callbackResultItem.Value;
                callbackHandler.Execute(args, filter, callbackResult);
            }
        }
        public TResult? RunCallbackWithResultFiltered<TArgs, TResult, TFilter>(CallbackTypeFiltered<TArgs, TResult, TFilter> callbackType, TArgs args, TResult? result, TFilter? filter)
        {
            if (handlers.TryGetValue(callbackType, out var handler))
            {
                var callbackHandler = (CallbackHandlerFiltered<TArgs, TResult, TFilter>)handler;
                using var callbackResultItem = CallbackResult<TResult>.Rent(result);
                var callbackResult = callbackResultItem.Value;
                callbackHandler.Execute(args, filter, callbackResult);
                result = callbackResult.GetValue();
            }
            return result;
        }

        public void AddCallback(ITrigger trigger)
        {
            var handler = handlers.GetOrAdd(trigger.Type, type => type.CreateHandler());
            handler.AddTrigger(trigger);
        }
        public bool RemoveCallback(ITrigger trigger)
        {
            if (handlers.TryGetValue(trigger.Type, out var handler))
            {
                var callbackHandler = handler;
                return callbackHandler.RemoveTrigger(trigger);
            }
            return false;
        }

        private readonly ConcurrentDictionary<ICallbackType, ICallbackHandler> handlers = new ConcurrentDictionary<ICallbackType, ICallbackHandler>();
    }
}
