#nullable enable // autogenerated

namespace PVZEngine.Callbacks
{
    public interface ICallbackRunner
    {
        void RunCallback<TArgs>(CallbackType<TArgs> callbackType, TArgs args);
        TResult? RunCallbackWithResult<TArgs, TResult>(CallbackType<TArgs> callbackType, TArgs args, TResult? result);
        void RunCallbackFiltered<TArgs>(CallbackType<TArgs> callbackType, TArgs args, object? filter);
        TResult? RunCallbackWithResultFiltered<TArgs, TResult>(CallbackType<TArgs> callbackType, TArgs args, TResult? result, object? filter);
    }
}
