#nullable enable // autogenerated

using System;

namespace PVZEngine.Callbacks
{
    public interface ICallbackRunner
    {
        void RunCallback<TArgs>(CallbackType<TArgs> callbackType, TArgs args);
        TResult? RunCallbackWithResult<TArgs, TResult>(CallbackType<TArgs, TResult> callbackType, TArgs args, TResult? result);
        void RunCallbackFiltered<TArgs, TFilter>(CallbackTypeFiltered<TArgs, TFilter> callbackType, TArgs args, TFilter? filter);
        TResult? RunCallbackWithResultFiltered<TArgs, TResult, TFilter>(CallbackTypeFiltered<TArgs, TResult, TFilter> callbackType, TArgs args, TResult? result, TFilter? filter);
    }
}
