#nullable enable // autogenerated

namespace PVZEngine.Callbacks
{
    public interface ITrigger
    {
        public ICallbackType Type { get; }
        public int Priority { get; }
    }
    public interface ITriggerFiltered<TFilter> : ITrigger
    {
        bool UseFilter { get; }
        TFilter? Filter { get; }
    }
}
