#nullable enable // autogenerated

using System;
using static UnityEngine.Networking.UnityWebRequest;

namespace PVZEngine.Callbacks
{
    public abstract class TriggerBase : ITrigger
    {
        public TriggerBase(int priority)
        {
            Priority = priority;
        }
        public abstract ICallbackType Type { get; }
        public int Priority { get; }
    }
    public class Trigger<TArgs> : TriggerBase
    {
        public CallbackType<TArgs> TypeGeneric { get; }
        public override ICallbackType Type => TypeGeneric;
        public Action<TArgs, CallbackResultVoid> Action { get; }

        public Trigger(CallbackType<TArgs> type, Action<TArgs, CallbackResultVoid> action, int priority) : base(priority)
        {
            TypeGeneric = type;
            Action = action;
        }
    }
    public class Trigger<TArgs, TResult> : TriggerBase
    {
        public CallbackType<TArgs, TResult> TypeGeneric { get; }
        public override ICallbackType Type => TypeGeneric;
        public Action<TArgs, CallbackResult<TResult>> Action { get; }

        public Trigger(CallbackType<TArgs, TResult> type, Action<TArgs, CallbackResult<TResult>> action, int priority) : base(priority)
        {
            TypeGeneric = type;
            Action = action;
        }
    }
    public class TriggerFiltered<TArgs, TFilter> : TriggerBase
    {
        public CallbackTypeFiltered<TArgs, TFilter> TypeGeneric { get; }
        public override ICallbackType Type => TypeGeneric;
        public Action<TArgs, CallbackResultVoid> Action { get; }
        public TFilter? Filter { get; }
        public bool UseFilter { get; }

        public TriggerFiltered(CallbackTypeFiltered<TArgs, TFilter> type, Action<TArgs, CallbackResultVoid> action, int priority) : base(priority)
        {
            TypeGeneric = type;
            Action = action;
            Filter = default;
        }
        public TriggerFiltered(CallbackTypeFiltered<TArgs, TFilter> type, Action<TArgs, CallbackResultVoid> action, int priority, TFilter? filter) : base(priority)
        {
            TypeGeneric = type;
            Action = action;
            Filter = filter;
            UseFilter = true;
        }
    }
    public class TriggerFiltered<TArgs, TResult, TFilter> : TriggerBase
    {
        public CallbackTypeFiltered<TArgs, TResult, TFilter> TypeGeneric { get; }
        public override ICallbackType Type => TypeGeneric;
        public Action<TArgs, CallbackResult<TResult>> Action { get; }
        public TFilter? Filter { get; }
        public bool UseFilter { get; }

        public TriggerFiltered(CallbackTypeFiltered<TArgs, TResult, TFilter> type, Action<TArgs, CallbackResult<TResult>> action, int priority) : base(priority)
        {
            TypeGeneric = type;
            Action = action;
            Filter = default;
        }
        public TriggerFiltered(CallbackTypeFiltered<TArgs, TResult, TFilter> type, Action<TArgs, CallbackResult<TResult>> action, int priority, TFilter? filter) : base(priority)
        {
            TypeGeneric = type;
            Action = action;
            Filter = filter;
            UseFilter = true;
        }
    }
}
