#nullable enable // autogenerated

using PVZEngine.Entities;
using PVZEngine.Grids;

namespace PVZEngine.Placements
{
    public abstract class SpawnCondition
    {
        public abstract NamespaceID? GetSpawnError(PlacementDefinition placement, LawnGrid grid, EntityDefinition entity);
        public abstract NamespaceID? GetTerrainSpawnErrorOfGrid(PlacementDefinition placement, LawnGrid grid, EntityDefinition entity);
        public abstract NamespaceID? GetEntitySpawnErrorOfGrid(PlacementDefinition placement, LawnGrid grid, EntityDefinition entity);
    }
}
