#nullable enable // autogenerated

namespace PVZEngine.Modifiers
{
    public abstract class ArrayModifier<T> : PropertyModifier<T>
    {
        public ArrayModifier(PropertyKey<T> propertyName, ArrayOperator op, T valueConst, int priority = 0) : base(propertyName, valueConst, priority)
        {
            Operator = op;
        }

        public ArrayModifier(PropertyKey<T> propertyName, ArrayOperator op, PropertyKey<T> buffPropertyName, int priority = 0) : base(propertyName, buffPropertyName, priority)
        {
            Operator = op;
        }
        public ArrayOperator Operator { get; private set; }
    }
}
