#nullable enable // autogenerated

namespace PVZEngine.Modifiers
{
    public enum ArrayOperator
    {
        Replace,
        Append,
        Prepend,
        Intersect,
        Union,
        Except
    }
}
