#nullable enable // autogenerated

using PVZEngine.Damages;
using PVZEngine.Definitions;

namespace PVZEngine.Shells
{
    public abstract class ShellDefinition : Definition
    {
        public ShellDefinition(string nsp, string name) : base(nsp, name)
        {
        }
        public virtual void EvaluateDamage(DamageInputPart input)
        {
        }
        public sealed override string GetDefinitionType() => EngineDefinitionTypes.SHELL;
    }
}
