#nullable enable // autogenerated

using System;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceArmor : BuffReference
    {
        public BuffReferenceArmor(long id, NamespaceID armorSlot, long buffId) : base(buffId)
        {
            entityID = id;
            this.armorSlot = armorSlot;
        }
        public override IBuffTarget? GetTarget(LevelEngine level)
        {
            return level.FindEntityByID(entityID)?.GetArmorAtSlot(armorSlot);
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceArmor other)
                return false;
            return buffId == other.buffId && entityID == other.entityID && armorSlot == other.armorSlot;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(buffId, entityID, armorSlot);
        }
        public long entityID;
        public NamespaceID armorSlot;
    }
}
