#nullable enable // autogenerated

using System;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public abstract class BuffReference
    {
        public BuffReference(long buffId)
        {
            this.buffId = buffId;
        }
        public abstract IBuffTarget? GetTarget(LevelEngine level);
        public Buff? GetBuff(LevelEngine level)
        {
            var target = GetTarget(level);
            if (target == null)
                return null;
            return target.GetBuff(buffId);
        }
        public long buffId;
    }
}
