#nullable enable // autogenerated

using System;
using MongoDB.Bson.Serialization.Attributes;
using PVZEngine.Level;
using PVZEngine.Tools.Cloning;

namespace PVZEngine.Buffs
{
    [Serializable]
    public abstract class BuffReference : ICanClone
    {
        public abstract IBuffTarget? GetTarget(LevelEngine level);
        public abstract object Clone();
        public Buff? GetBuff(LevelEngine level)
        {
            var target = GetTarget(level);
            if (target == null)
                return null;
            return target.GetBuff(BuffId);
        }
        public abstract long BuffId { get; }
    }
}
