#nullable enable // autogenerated

using System;
using MongoDB.Bson.Serialization.Attributes;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceLawnGrid : IBuffReference
    {
        public BuffReferenceLawnGrid(int gridIndex, long buffId)
        {
            this.TileIndex = gridIndex;
            this.BuffID = buffId;
        }
        public Buff? GetBuff(LevelEngine level)
        {
            return level.GetGrid(TileIndex)?.GetBuff(BuffID);
        }
        public object Clone()
        {
            return new BuffReferenceEntity(TileIndex, BuffID);
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceLawnGrid other)
                return false;
            return BuffID == other.BuffID && TileIndex == other.TileIndex;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(BuffID, TileIndex);
        }
        [BsonElement("gridIndex")]
        public int TileIndex { get; private set; }
        [BsonElement("buffId")]
        public long BuffID { get; private set; }
    }
}
