#nullable enable // autogenerated

using System;
using MongoDB.Bson.Serialization.Attributes;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceEntity : BuffReference
    {
        public BuffReferenceEntity(long id, long buffId)
        {
            entityID = id;
            this.buffId = buffId;
        }
        public override IBuffTarget? GetTarget(LevelEngine level)
        {
            return level.FindEntityByID(EntityID);
        }
        public override object Clone()
        {
            return new BuffReferenceEntity(EntityID, BuffId);
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceEntity other)
                return false;
            return BuffId == other.BuffId && EntityID == other.EntityID;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(BuffId, EntityID);
        }
        [BsonIgnore]
        public long EntityID => entityID;
        [BsonElement]
        private long entityID;
        [BsonIgnore]
        public override long BuffId => buffId;
        [BsonElement]
        private long buffId;
    }
}
