#nullable enable // autogenerated

using System;
using MongoDB.Bson.Serialization.Attributes;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceLawnGrid : BuffReference
    {
        public BuffReferenceLawnGrid(int gridIndex, long buffId)
        {
            this.gridIndex = gridIndex;
            this.buffId = buffId;
        }
        public override IBuffTarget? GetTarget(LevelEngine level)
        {
            return level.GetGrid(TileIndex);
        }
        public override object Clone()
        {
            return new BuffReferenceEntity(TileIndex, BuffId);
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceLawnGrid other)
                return false;
            return BuffId == other.BuffId && TileIndex == other.TileIndex;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(BuffId, TileIndex);
        }
        [BsonIgnore]
        public int TileIndex => gridIndex;
        [BsonElement]
        private int gridIndex;
        [BsonIgnore]
        public override long BuffId => buffId;
        [BsonElement]
        private long buffId;
    }
}
