#nullable enable // autogenerated

using System;
using MongoDB.Bson.Serialization.Attributes;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceArmor : BuffReference
    {
        public BuffReferenceArmor(long id, NamespaceID armorSlot, long buffId)
        {
            entityID = id;
            this.armorSlot = armorSlot;
            this.buffId = buffId;
        }
        public override IBuffTarget? GetTarget(LevelEngine level)
        {
            return level.FindEntityByID(EntityID)?.GetArmorAtSlot(ArmorSlot);
        }
        public override object Clone()
        {
            return new BuffReferenceArmor(EntityID, ArmorSlot, BuffId);
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceArmor other)
                return false;
            return BuffId == other.BuffId && EntityID == other.EntityID && ArmorSlot == other.ArmorSlot;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(BuffId, EntityID, ArmorSlot);
        }
        [BsonIgnore]
        public long EntityID => entityID;
        [BsonElement]
        private long entityID;
        [BsonIgnore]
        public NamespaceID ArmorSlot => armorSlot;
        [BsonElement]
        private NamespaceID armorSlot;
        [BsonIgnore]
        public override long BuffId => buffId;
        [BsonElement]
        private long buffId;
    }
}
