#nullable enable // autogenerated

using System;
using MongoDB.Bson.Serialization.Attributes;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceLevel : BuffReference
    {
        public BuffReferenceLevel(long buffId)
        {
            this.buffId = buffId;
        }
        public override IBuffTarget? GetTarget(LevelEngine level)
        {
            return level;
        }
        public override object Clone()
        {
            return new BuffReferenceLevel(BuffId);
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceLevel other)
                return false;
            return BuffId == other.BuffId;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(BuffId);
        }
        [BsonIgnore]
        public override long BuffId => buffId;
        [BsonElement]
        private long buffId;
    }
}
