#nullable enable // autogenerated

using System;
using MongoDB.Bson.Serialization.Attributes;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceConveyorSeedPack : IBuffReference
    {
        public BuffReferenceConveyorSeedPack(long seedId, long buffId)
        {
            this.SeedID = seedId;
            this.BuffID = buffId;
        }
        public Buff? GetBuff(LevelEngine level)
        {
            return level.GetConveyorSeedPackByID(SeedID)?.GetBuff(BuffID);
        }
        public object Clone()
        {
            return new BuffReferenceConveyorSeedPack(SeedID, BuffID);
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceConveyorSeedPack other)
                return false;
            return BuffID == other.BuffID && SeedID == other.SeedID;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(SeedID, BuffID);
        }
        [BsonElement("buffId")]
        public long BuffID { get; private set; }
        [BsonElement("seedId")]
        public long SeedID { get; private set; }
    }
}
