#nullable enable // autogenerated

using System;
using MongoDB.Bson.Serialization.Attributes;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceArmor : IBuffReference
    {
        public BuffReferenceArmor(long id, NamespaceID armorSlot, long buffId)
        {
            EntityID = id;
            this.ArmorSlot = armorSlot;
            this.BuffID = buffId;
        }
        public Buff? GetBuff(LevelEngine level)
        {
            return level.FindEntityByID(EntityID)?.GetArmorAtSlot(ArmorSlot)?.GetBuff(BuffID);
        }
        public object Clone()
        {
            return new BuffReferenceArmor(EntityID, ArmorSlot, BuffID);
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceArmor other)
                return false;
            return BuffID == other.BuffID && EntityID == other.EntityID && ArmorSlot == other.ArmorSlot;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(BuffID, EntityID, ArmorSlot);
        }
        [BsonElement("entityID")]
        public long EntityID { get; private set; }
        [BsonElement("armorSlot")]
        public NamespaceID ArmorSlot { get; private set; }
        [BsonElement("buffId")]
        public long BuffID { get; private set; }
    }
}
