#nullable enable // autogenerated

using System;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceEntity : BuffReference
    {
        public BuffReferenceEntity(long id, long buffId) : base(buffId)
        {
            entityID = id;
        }
        public override IBuffTarget? GetTarget(LevelEngine level)
        {
            return level.FindEntityByID(entityID);
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceEntity other)
                return false;
            return buffId == other.buffId && entityID == other.entityID;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(buffId, entityID);
        }
        public long entityID;
    }
}
