#nullable enable // autogenerated

using System;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceLawnGrid : BuffReference
    {
        public BuffReferenceLawnGrid(int gridIndex, long buffId) : base(buffId)
        {
            this.gridIndex = gridIndex;
        }
        public override IBuffTarget? GetTarget(LevelEngine level)
        {
            return level.GetGrid(gridIndex);
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceLawnGrid other)
                return false;
            return buffId == other.buffId && gridIndex == other.gridIndex;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(buffId, gridIndex);
        }
        public int gridIndex;
    }
}
