#nullable enable // autogenerated

using System;
using MongoDB.Bson.Serialization.Attributes;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceClassicSeedPack : BuffReference
    {
        public BuffReferenceClassicSeedPack(long seedId, long buffId)
        {
            this.seedId = seedId;
            this.buffId = buffId;
        }
        public override IBuffTarget? GetTarget(LevelEngine level)
        {
            return level.GetSeedPackByID(SeedID);
        }
        public override object Clone()
        {
            return new BuffReferenceClassicSeedPack(SeedID, BuffId);
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceClassicSeedPack other)
                return false;
            return BuffId == other.BuffId && SeedID == other.SeedID;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(SeedID, BuffId);
        }
        [BsonIgnore]
        public override long BuffId => buffId;
        [BsonElement]
        private long buffId;
        [BsonIgnore]
        public long SeedID => seedId;
        [BsonElement]
        private long seedId;
    }
}
