#nullable enable // autogenerated

using System;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceLevel : BuffReference
    {
        public BuffReferenceLevel(long buffId) : base(buffId)
        {
        }
        public override IBuffTarget? GetTarget(LevelEngine level)
        {
            return level;
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceLevel other)
                return false;
            return buffId == other.buffId;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(buffId);
        }
    }
}
