#nullable enable // autogenerated

using System;
using MongoDB.Bson.Serialization.Attributes;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceEntity : IBuffReference
    {
        public BuffReferenceEntity(long id, long buffId)
        {
            EntityID = id;
            this.BuffID = buffId;
        }
        public Buff? GetBuff(LevelEngine level)
        {
            return level.FindEntityByID(EntityID)?.GetBuff(BuffID);
        }
        public object Clone()
        {
            return new BuffReferenceEntity(EntityID, BuffID);
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceEntity other)
                return false;
            return BuffID == other.BuffID && EntityID == other.EntityID;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(BuffID, EntityID);
        }
        [BsonElement("entityID")]
        public long EntityID { get; private set; }
        [BsonElement("buffId")]
        public long BuffID { get; private set; }
    }
}
