#nullable enable // autogenerated

using System;
using MongoDB.Bson.Serialization.Attributes;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceLevel : IBuffReference
    {
        public BuffReferenceLevel(long buffId)
        {
            this.BuffID = buffId;
        }
        public Buff? GetBuff(LevelEngine level)
        {
            return level.GetBuff(BuffID);
        }
        public object Clone()
        {
            return new BuffReferenceLevel(BuffID);
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceLevel other)
                return false;
            return BuffID == other.BuffID;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(BuffID);
        }
        [BsonElement("buffId")]
        public long BuffID { get; private set; }
    }
}
