#nullable enable // autogenerated

using System;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    [Serializable]
    public class BuffReferenceClassicSeedPack : BuffReferenceSeedPack
    {
        public BuffReferenceClassicSeedPack(long seedId, long buffId) : base(seedId, buffId)
        {
        }
        public override IBuffTarget? GetTarget(LevelEngine level)
        {
            return level.GetSeedPackByID(seedID);
        }
        public override bool Equals(object obj)
        {
            if (obj is not BuffReferenceClassicSeedPack other)
                return false;
            return buffId == other.buffId && seedID == other.seedID;
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(seedID, buffId);
        }
    }
}
