#nullable enable // autogenerated

using System;

namespace PVZEngine.Buffs
{
    [Serializable]
    public abstract class BuffReferenceSeedPack : BuffReference
    {
        public BuffReferenceSeedPack(long seedId, long buffId) : base(buffId)
        {
            seedID = seedId;
        }
        public long seedID;
    }
}
