#nullable enable // autogenerated

using PVZEngine.Level;
using PVZEngine.Tools.Cloning;

namespace PVZEngine.Buffs
{
    public interface IBuffReference : ICanClone
    {
        Buff? GetBuff(LevelEngine level);
    }
}
