#nullable enable // autogenerated

using System.Collections.Generic;

namespace PVZEngine.Level
{
    public class ConveyorSeedSpendRecords
    {
        public void SetSpendValue(NamespaceID id, int value)
        {
            var entry = entries.Find(e => e.id == id);
            if (entry == null)
            {
                entry = new ConveyorSeedSendRecordEntry(id)
                {
                    spend = value
                };
                entries.Add(entry);
            }
            else
            {
                entry.spend = value;
            }
        }
        public void AddSpendValue(NamespaceID id, int value)
        {
            SetSpendValue(id, GetSpendValue(id) + value);
        }
        public int GetSpendValue(NamespaceID id)
        {
            var entry = entries.Find(e => e.id == id);
            return entry?.spend ?? 0;
        }
        public void SetSeedCountInDiscardPile(NamespaceID id, int value)
        {
            var entry = entries.Find(e => e.id == id);
            if (entry == null)
            {
                entry = new ConveyorSeedSendRecordEntry(id)
                {
                    discardCount = value
                };
                entries.Add(entry);
            }
            else
            {
                entry.discardCount = value;
            }
        }
        public void AddToDiscardPile(NamespaceID id, int value)
        {
            SetSeedCountInDiscardPile(id, GetSeedCountInDiscardPile(id) + value);
        }
        public int GetSeedCountInDiscardPile(NamespaceID id)
        {
            var entry = entries.Find(e => e.id == id);
            return entry?.discardCount ?? 0;
        }
        public SerializableConveyorSeedSpendRecords ToSerializable()
        {
            var seriEntries = new SerializableConveyorSeedSendRecordEntry[entries.Count];
            for (int i = 0; i < seriEntries.Length; i++)
            {
                seriEntries[i] = entries[i].ToSerializable();
            }
            return new SerializableConveyorSeedSpendRecords()
            {
                entries = seriEntries
            };
        }
        public static ConveyorSeedSpendRecords ToDeserialized(SerializableConveyorSeedSpendRecords? seri)
        {
            var entries = new List<ConveyorSeedSendRecordEntry>();
            if (seri != null && seri.entries != null)
            {
                foreach (var seriEntry in seri.entries)
                {
                    if (seriEntry == null)
                        continue;
                    var entry = ConveyorSeedSendRecordEntry.ToDeserialized(seriEntry);
                    if (entry == null)
                        continue;
                    entries.Add(entry);
                }
            }
            return new ConveyorSeedSpendRecords()
            {
                entries = entries
            };
        }
        private List<ConveyorSeedSendRecordEntry> entries = new List<ConveyorSeedSendRecordEntry>();
    }
    public class ConveyorSeedSendRecordEntry
    {
        public ConveyorSeedSendRecordEntry(NamespaceID id)
        {
            this.id = id;
        }
        public SerializableConveyorSeedSendRecordEntry ToSerializable()
        {
            return new SerializableConveyorSeedSendRecordEntry()
            {
                id = id,
                spend = spend,
                discardCount = discardCount
            };
        }
        public static ConveyorSeedSendRecordEntry? ToDeserialized(SerializableConveyorSeedSendRecordEntry? seri)
        {
            if (seri == null || !NamespaceID.IsValid(seri.id))
                return null;
            return new ConveyorSeedSendRecordEntry(seri.id)
            {
                spend = seri.spend,
                discardCount = seri.discardCount
            };
        }
        public NamespaceID id;
        public int spend;
        public int discardCount;
    }
}
