#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using PVZEngine.SeedPacks;
using PVZEngine.Tools;

namespace PVZEngine.Level
{
    public partial class LevelEngine
    {
        #region 创建种子包
        public ClassicSeedPack? CreateSeedPack(NamespaceID id)
        {
            var def = Content.GetSeedDefinition(id);
            if (def == null)
                return null;
            return new ClassicSeedPack(this, def, AllocSeedPackID());
        }
        public void InsertSeedPackAt(int index, ClassicSeedPack seed)
        {
            if (index < 0 || index >= seedPacks.Length)
                return;
            if (seedPacks[index] != null)
                return;
            seedPacks[index] = seed;
            IncreaseLevelObjectReference(seed);
            OnSeedAdded?.Invoke(index);
        }
        private long AllocSeedPackID()
        {
            var id = currentSeedPackID;
            currentSeedPackID++;
            return id;
        }
        #endregion

        #region 移除种子包
        public bool RemoveSeedPackAt(int index)
        {
            if (index < 0 || index >= seedPacks.Length)
                return false;
            var seedPack = seedPacks[index];
            if (seedPack == null)
                return false;
            seedPacks[index] = null;
            DecreaseLevelObjectReference(seedPack);
            OnSeedRemoved?.Invoke(index);
            return true;
        }
        public void ClearSeedPacks()
        {
            for (int i = 0; i < GetSeedSlotCount(); i++)
            {
                RemoveSeedPackAt(i);
            }
        }
        #endregion

        #region 替换种子包
        public void ReplaceSeedPackAt(int index, ClassicSeedPack? seed)
        {
            if (index < 0 || index >= GetSeedSlotCount())
                return;
            RemoveSeedPackAt(index);
            if (seed != null)
                InsertSeedPackAt(index, seed);
        }
        public void ReplaceSeedPacks(IList<ClassicSeedPack> targetsID)
        {
            var targetCount = targetsID.Count;
            for (int i = 0; i < GetSeedSlotCount(); i++)
            {
                var seed = i < targetCount ? targetsID[i] : null;
                ReplaceSeedPackAt(i, seed);
            }
        }
        #endregion

        #region 获取种子包位置
        public int GetSeedPackIndex(ClassicSeedPack seed)
        {
            return Array.IndexOf(seedPacks, seed);
        }
        public int GetSeedPackIndex(NamespaceID id)
        {
            return Array.FindIndex(seedPacks, s => s != null && s.GetDefinitionID() == id);
        }
        #endregion

        #region 获取种子包数量
        public int GetSeedPackCount()
        {
            int count = 0;
            foreach (var seedPack in seedPacks)
            {
                if (seedPack != null)
                    count++;
            }
            return count;
        }
        public int GetSeedSlotCount()
        {
            return seedPacks.Length;
        }
        public void SetSeedSlotCount(int count)
        {
            if (count < seedPacks.Length)
            {
                for (int i = count; i < seedPacks.Length; i++)
                {
                    RemoveSeedPackAt(i);
                }
            }
            Array.Resize(ref seedPacks, count);
            OnSeedSlotCountChanged?.Invoke(count);
        }
        #endregion

        #region 获取种子包
        public void GetAllSeedPacks(List<ClassicSeedPack?> results)
        {
            results.AddRange(seedPacks);
        }
        public ClassicSeedPack? GetSeedPackAt(int index)
        {
            if (index < 0 || index >= seedPacks.Length)
                return null;
            return seedPacks[index];
        }
        public ClassicSeedPack? GetSeedPack(NamespaceID seedRef)
        {
            foreach (var seedPack in seedPacks)
            {
                if (seedPack != null && seedPack.GetDefinitionID() == seedRef)
                    return seedPack;
            }
            return null;
        }
        public ClassicSeedPack? GetSeedPackByID(long id)
        {
            foreach (var seedPack in seedPacks)
            {
                if (seedPack != null && seedPack.ID == id)
                    return seedPack;
            }
            return null;
        }
        #endregion

        #region 更新
        private void UpdateClassicSeedPacks(float rechargeSpeed)
        {
            foreach (var seedPack in seedPacks)
            {
                if (seedPack == null)
                    continue;
                seedPack.Update(rechargeSpeed);
            }
        }
        #endregion

        #region 充能
        /// <summary>
        /// 重置所有卡牌重装填进度。
        /// </summary>
        public void ResetAllRechargeProgress()
        {
            foreach (var seedPack in seedPacks)
            {
                if (seedPack == null)
                    continue;
                seedPack.SetStartRecharge(true);
                seedPack.ResetRecharge();
            }
        }
        public void FullRechargeAll()
        {
            foreach (var seedPack in seedPacks)
            {
                if (seedPack == null)
                    continue;
                seedPack.FullRecharge();
            }
        }
        #endregion

        #region 序列化
        private void WriteSeedPacksToSerializable(SerializableLevel seri)
        {
            seri.currentSeedPackID = currentSeedPackID;
            seri.seedPacks = new SerializableClassicSeedPack[seedPacks.Length];
            for (int i = 0; i < seri.seedPacks.Length; i++)
            {
                var seedPack = seedPacks[i];
                seri.seedPacks[i] = seedPack != null ? seedPack.ToSerializable() : null;
            }
        }
        private void CreateSeedPacksFromSerializable(SerializableLevel seri)
        {
            currentSeedPackID = seri.currentSeedPackID;
            if (seri.seedPacks != null)
            {
                seedPacks = new ClassicSeedPack[seri.seedPacks.Length];
                for (int i = 0; i < seedPacks.Length; i++)
                {
                    var seriSeedPack = seri.seedPacks[i];
                    seedPacks[i] = seriSeedPack != null ? ClassicSeedPack.CreateFromSerializable(seriSeedPack, this) : null;
                }
            }
        }
        private void ReadSeedPacksFromSerializable(SerializableLevel seri)
        {
            foreach (var seed in seedPacks)
            {
                if (seed == null)
                    continue;
                SerializableClassicSeedPack? seriSeed = null;
                if (seri.seedPacks != null)
                {
                    foreach (var seriPack in seri.seedPacks)
                    {
                        if (seriPack != null && seriPack.id == seed.ID)
                        {
                            seriSeed = seriPack;
                            break;
                        }
                    }
                }
                if (seriSeed == null)
                    continue;
                seed.LoadFromSerializable(this, seriSeed);
                IncreaseLevelObjectReference(seed, true);
            }
        }
        #endregion

        public event Action<int>? OnSeedAdded;
        public event Action<int>? OnSeedRemoved;
        public event Action<int>? OnSeedSlotCountChanged;

        private long currentSeedPackID = 1;
        private ClassicSeedPack?[] seedPacks = Array.Empty<ClassicSeedPack>();
    }
}
