#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Entities;
using PVZEngine.Tools;
using UnityEngine;

namespace PVZEngine.Level
{
    public partial class LevelEngine
    {
        public void SetEnergy(float value)
        {
            Energy = Mathf.Clamp(value, 0, this.GetMaxEnergy());
        }
        public void AddEnergy(float value)
        {
            SetEnergy(Energy + value);
        }
        public void AddEnergyDelayed(Entity source, float value)
        {
            if (value == 0)
                return;
            var before = Energy;
            AddEnergy(value);
            var added = Energy - before;
            delayedEnergyEntities.Add(source, added);
        }
        public bool RemoveEnergyDelayedEntity(Entity entity)
        {
            return delayedEnergyEntities.Remove(entity);
        }
        public void ClearEnergyDelayedEntities()
        {
            delayedEnergyEntities.Clear();
        }
        public float GetDelayedEnergy()
        {
            float sum = 0;
            foreach (var pair in delayedEnergyEntities)
            {
                sum += pair.Value;
            }
            return sum;
        }
        private void UpdateDelayedEnergyEntities()
        {
            if (delayedEnergyEntities.Count == 0)
                return;

            using var toRemoveItem = ListPool<Entity>.Rent();
            List<Entity> toRemove = toRemoveItem.Value;
            foreach (var pair in delayedEnergyEntities)
            {
                if (!pair.Key.Exists())
                {
                    toRemove.Add(pair.Key);
                }
            }
            foreach (var e in toRemove)
                delayedEnergyEntities.Remove(e);
        }
        public float Energy { get; private set; }
        private Dictionary<Entity, float> delayedEnergyEntities = new Dictionary<Entity, float>();
    }
}