#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using PVZEngine.SeedPacks;
using PVZEngine.Tools;
using PVZEngine.Tools.Random;
using UnityEngine;

namespace PVZEngine.Level
{
    public partial class LevelEngine
    {
        #region 添加种子包
        public bool CanConveySeedPack()
        {
            return conveyorSeedPacks.Count < GetConveyorSlotCount();
        }
        public ConveyorSeedPack? AddConveyorSeedPack(NamespaceID id)
        {
            return InsertConveyorSeedPackAt(conveyorSeedPacks.Count, id);
        }
        public ConveyorSeedPack? InsertConveyorSeedPackAt(int index, NamespaceID id)
        {
            if (index < 0 || index > conveyorSeedPacks.Count || index >= GetConveyorSlotCount())
                return null;
            var seedDefinition = Content.GetSeedDefinition(id);
            if (seedDefinition == null)
                return null;
            var seedPack = new ConveyorSeedPack(this, seedDefinition, AllocSeedPackID());
            conveyorSeedPacks.Insert(index, seedPack);
            IncreaseLevelObjectReference(seedPack);
            OnConveyorSeedAdded?.Invoke(index);
            return seedPack;
        }
        #endregion

        #region 删除种子包
        public bool RemoveConveyorSeedPackAt(int index)
        {
            if (index < 0 || index >= conveyorSeedPacks.Count)
                return false;
            var seedPack = conveyorSeedPacks[index];
            conveyorSeedPacks.RemoveAt(index);
            DecreaseLevelObjectReference(seedPack);
            OnConveyorSeedRemoved?.Invoke(index);
            return true;
        }
        public void ClearConveyorSeedPacks()
        {
            for (int i = conveyorSeedPacks.Count - 1; i >= 0; i--)
            {
                RemoveConveyorSeedPackAt(i);
            }
        }
        #endregion

        #region 更新种子包
        public void UpdateConveyorSeedPacks(float rechargeSpeed)
        {
            foreach (var seedPack in conveyorSeedPacks)
            {
                if (seedPack == null)
                    continue;
                seedPack.Update(rechargeSpeed);
            }
        }
        #endregion

        #region 获取种子包位置
        public int GetConveyorSeedPackIndex(ConveyorSeedPack seed)
        {
            return conveyorSeedPacks.IndexOf(seed);
        }
        public int GetConveyorSeedPackIndex(NamespaceID id)
        {
            return conveyorSeedPacks.FindIndex(s => s.GetDefinitionID() == id);
        }
        #endregion

        #region 获取种子包数量
        public int GetConveyorSeedPackCount()
        {
            int count = 0;
            foreach (var seedPack in conveyorSeedPacks)
            {
                if (seedPack != null)
                    count++;
            }
            return count;
        }
        #endregion

        #region 获取种子包
        public void GetAllConveyorSeedPacks(List<ConveyorSeedPack> results)
        {
            results.AddRange(conveyorSeedPacks);
        }
        public ConveyorSeedPack? GetConveyorSeedPackAt(int index)
        {
            if (index < 0 || index >= conveyorSeedPacks.Count)
                return null;
            return conveyorSeedPacks[index];
        }
        public ConveyorSeedPack? GetConveyorSeedPack(NamespaceID seedRef)
        {
            foreach (var seedPack in conveyorSeedPacks)
            {
                if (seedPack != null && seedPack.GetDefinitionID() == seedRef)
                    return seedPack;
            }
            return null;
        }
        public ConveyorSeedPack? GetConveyorSeedPackByID(long id)
        {
            foreach (var seedPack in conveyorSeedPacks)
            {
                if (seedPack.ID == id)
                    return seedPack;
            }
            return null;
        }
        #endregion

        #region 上限
        public int GetConveyorSlotCount()
        {
            return conveyorSlotCount;
        }
        public void SetConveyorSlotCount(int value)
        {
            conveyorSlotCount = value;
            OnConveyorSeedSlotCountChanged?.Invoke(value);
        }
        #endregion

        #region 占用情况
        public SeedPack? ConveyRandomSeedPack(IConveyorPoolEntry[] entries)
        {
            if (CanConveySeedPack())
            {
                var id = DrawConveyorSeed(entries);
                if (id == null)
                    return null;
                var seedPack = AddConveyorSeedPack(id);
                if (seedPack != null)
                {
                    seedPack.SetDrawnConveyorSeed(seedPack.GetDefinitionID());
                    return seedPack;
                }
                else
                {
                    PutSeedToConveyorDrawPile(id);
                }
            }
            return null;
        }
        public NamespaceID? DrawConveyorSeed(IConveyorPoolEntry[] entries)
        {
            if (entries.Length <= 0)
                return null;
            var rng = GetConveyorRNG();
            if (IsConveyorPoolEmpty(entries))
            {
                RefillConveyorPool(entries);
            }
            if (IsConveyorPoolEmpty(entries))
            {
                return null;
            }
            var weights = new int[entries.Length];
            for (int i = 0; i < weights.Length; i++)
            {
                var e = entries[i];
                weights[i] = Mathf.Max(0, GetSeedCountFromConveyorDrawPile(e.ID, e.Count));
            }
            var entry = entries.WeightedRandom(weights, rng);
            TakeSeedFromConveyorDrawPile(entry.ID);
            return entry.ID;
        }
        public bool IsConveyorPoolEmpty(IConveyorPoolEntry[] entries)
        {
            foreach (var e in entries)
            {
                if (GetSeedCountFromConveyorDrawPile(e.ID, e.Count) > 0)
                    return false;
            }
            return true;
        }
        public void RefillConveyorPool(IConveyorPoolEntry[] entries)
        {
            foreach (var entry in entries)
            {
                var id = entry.ID;
                var drawCount = GetSeedCountFromConveyorDrawPile(id, entry.Count);
                var discardCount = GetSeedCountInConveyorDiscardPile(id);
                int fillCount = Mathf.Max(entry.MinCount, discardCount);
                if (fillCount > 0)
                {
                    TakeSeedFromConveyorDiscardPile(id, fillCount);
                    PutSeedToConveyorDrawPile(id, fillCount);
                }
            }
        }
        public void PutSeedToConveyorDiscardPile(NamespaceID seedID, int value = 1)
        {
            conveyorSeedSpendRecord.AddToDiscardPile(seedID, value);
        }
        public void TakeSeedFromConveyorDiscardPile(NamespaceID seedID, int value = 1)
        {
            conveyorSeedSpendRecord.AddToDiscardPile(seedID, -value);
        }
        public int GetSeedCountInConveyorDiscardPile(NamespaceID seedID)
        {
            return conveyorSeedSpendRecord.GetSeedCountInDiscardPile(seedID);
        }
        public void PutSeedToConveyorDrawPile(NamespaceID seedID, int value = 1)
        {
            conveyorSeedSpendRecord.AddSpendValue(seedID, -value);
        }
        public void TakeSeedFromConveyorDrawPile(NamespaceID seedID, int value = 1)
        {
            conveyorSeedSpendRecord.AddSpendValue(seedID, value);
        }
        public int GetSeedCountFromConveyorDrawPile(NamespaceID seedID, int entryCount)
        {
            return entryCount - conveyorSeedSpendRecord.GetSpendValue(seedID);
        }
        #endregion

        #region 序列化
        public void WriteConveyorToSerializable(SerializableLevel seri)
        {
            using var seriConveyorSeedPacksItem = ListPool<SerializableConveyorSeedPack>.Rent();
            var seriConveyorSeedPacks = seriConveyorSeedPacksItem.Value;
            foreach (var seedPack in conveyorSeedPacks)
            {
                if (seedPack == null)
                    continue;
                seriConveyorSeedPacks.Add(seedPack.ToSerializable());
            }
            seri.conveyorSeedPacks = seriConveyorSeedPacks.ToArray();
            seri.conveyorSlotCount = conveyorSlotCount;
            seri.conveyorSeedSpendRecord = conveyorSeedSpendRecord.ToSerializable();
        }
        public void CreateConveyorFromSerializable(SerializableLevel seri)
        {
            conveyorSlotCount = seri.conveyorSlotCount;
            conveyorSeedSpendRecord = ConveyorSeedSpendRecords.ToDeserialized(seri.conveyorSeedSpendRecord);
            conveyorSeedPacks.Clear();
            if (seri.conveyorSeedPacks != null)
            {
                foreach (var seriSeedPack in seri.conveyorSeedPacks)
                {
                    var seedPack = ConveyorSeedPack.CreateFromSerializable(seriSeedPack, this);
                    if (seedPack == null)
                        continue;
                    conveyorSeedPacks.Add(seedPack);
                }
            }
        }
        public void ReadConveyorFromSerializable(SerializableLevel seri)
        {
            foreach (var seed in conveyorSeedPacks)
            {
                if (seed == null)
                    continue;
                SerializableConveyorSeedPack? seriSeed = null;
                if (seri.conveyorSeedPacks != null)
                {
                    foreach (var seriSeedPack in seri.conveyorSeedPacks)
                    {
                        if (seriSeedPack != null && seriSeedPack.id == seed.ID)
                        {
                            seriSeed = seriSeedPack;
                        }
                    }
                }
                if (seriSeed == null)
                    continue;
                seed.LoadFromSerializable(this, seriSeed);
                IncreaseLevelObjectReference(seed, true);
            }
        }
        #endregion


        public event Action<int>? OnConveyorSeedAdded;
        public event Action<int>? OnConveyorSeedRemoved;
        public event Action<int>? OnConveyorSeedSlotCountChanged;

        private int conveyorSlotCount = 10;
        private List<ConveyorSeedPack> conveyorSeedPacks = new List<ConveyorSeedPack>();
        private ConveyorSeedSpendRecords conveyorSeedSpendRecord = new ConveyorSeedSpendRecords();
    }
}
