#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using PVZEngine.Modifiers;

namespace PVZEngine.Level
{
    public partial class LevelEngine : IModifierSource, IModifierProvider
    {
        private void ReevaluateModifierCaches()
        {
            modifierLibrary.ClearModifierCaches();
            for (int i = 0; i < AreaDefinition.GetModifierCount(); i++)
            {
                var modifier = AreaDefinition.GetModifierAt(i);
                modifierLibrary.AddModifierCache(new ModifierSourceItem(this, modifier));
            }
            for (int b = 0; b < StageDefinition.GetBehaviourCount(); b++)
            {
                var behaviour = StageDefinition.GetBehaviourAt(b);
                for (int i = 0; i < behaviour.GetModifierCount(); i++)
                {
                    var modifier = behaviour.GetModifierAt(i);
                    modifierLibrary.AddModifierCache(new ModifierSourceItem(this, modifier));
                }
            }
        }
        private void OnModifiedPropertyNeedsUpdateCallback(IPropertyKey name)
        {
            OnModifiedPropertyNeedsUpdate?.Invoke(name);
        }
        T? IModifierSource.GetProperty<T>(PropertyKey<T> name) where T : default
        {
            return GetProperty<T>(name);
        }

        IEnumerable<IPropertyKey> IModifierProvider.GetModifiedProperties()
        {
            return modifierLibrary.GetModifyPropertyKeys();
        }

        void IModifierProvider.GetModifiersForProperty(IPropertyKey name, List<ModifierSourceItem> results)
        {
            modifierLibrary.GetModifierItemsForProperty(name, results);
        }

        public event Action<IPropertyKey>? OnModifiedPropertyNeedsUpdate;
        private ModifierLibrary modifierLibrary;
    }
}