#nullable enable // autogenerated

using System;
using PVZEngine.Entities;
using UnityEngine;

namespace PVZEngine.Level
{
    public class SpawnParams
    {
        public void SetProperty<T>(PropertyKey<T> key, T? value)
        {
            properties.SetProperty(key, value);
        }
        public void Apply(Entity entity)
        {
            if (EntityParent != null)
            {
                entity.SetParent(EntityParent);
            }
            if (EntityTarget != null)
            {
                entity.Target = EntityTarget;
            }
            entity.Velocity = EntityVelocity;
            foreach (var property in properties.GetPropertyNames())
            {
                entity.SetPropertyObject(property, properties.GetPropertyObject(property));
            }
            OnApply?.Invoke(entity);
        }
        public event Action<Entity>? OnApply;
        public Entity? EntityParent { get; set; }
        public Entity? EntityTarget { get; set; }
        public Vector3 EntityVelocity { get; set; }
        private PropertyDictionary properties = new PropertyDictionary();
    }
}
