#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Buffs;
using PVZEngine.Level;
using PVZEngine.Tools;
using PVZEngine.Tools.Timing;

namespace PVZEngine.Auras
{
    public class AuraEffect
    {
        public AuraEffect(AuraEffectDefinition definition, int id, IAuraSource source)
        {
            ID = id;
            Definition = definition;
            updateTimer = new FrameTimer(Definition.UpdateInterval);
            Source = source;
        }
        public void UpdateAuraInterval()
        {
            if (ShouldAutoUpdateAura())
            {
                updateTimer.Run();
                if (updateTimer.Expired)
                {
                    updateTimer.Reset();
                    UpdateAura();
                }
            }
        }
        public void PostAdd()
        {
            if (ShouldAutoUpdateAura())
            {
                UpdateAura();
            }
            Definition.PostAdd(this);
        }
        public void PostRemove()
        {
            ClearBuffs();
            Definition.PostRemove(this);
        }
        public bool ShouldAutoUpdateAura()
        {
            return updateTimer.MaxFrame > 0;
        }
        public int GetTargetCount()
        {
            return buffCaches.Count;
        }
        public void UpdateAura()
        {
            if (!Source.Exists())
                return;
            var level = Source.GetLevel();
            targetsBuffer.Clear();
            Definition.GetAuraTargets(this, targetsBuffer);
            foreach (var target in targetsBuffer)
            {
                var buff = GetTargetBuff(target);
                if (buff == null || buff.Target == null || !buff.Target.Exists())
                {
                    buff = AddTargetBuff(target);
                }
                Definition.UpdateTargetBuff(this, target, buff);
            }

            removeBuffBuffer.Clear();
            foreach (var pair in buffCaches)
            {
                var target = pair.Key;
                if (!target.Exists() || !targetsBuffer.Contains(target))
                {
                    var buff = pair.Value;
                    target.RemoveBuff(buff);
                    removeBuffBuffer.Add(target);
                }
            }
            for (int i = 0; i < removeBuffBuffer.Count; i++)
            {
                buffCaches.Remove(removeBuffBuffer[i]);
            }
        }
        public AuraEffect Clone(int id)
        {
            return new AuraEffect(Definition, id, Source);
        }
        public SerializableAuraEffect ToSerializable()
        {
            using var buffReferencesBufferItem = ListPool<IBuffReference>.Rent();
            var buffer = buffReferencesBufferItem.Value;
            foreach (var pair in buffCaches)
            {
                buffer.Add(pair.Key.GetBuffReference(pair.Value));
            }
            return new SerializableAuraEffect()
            {
                id = ID,
                buffs = buffer.ToArray(),
                updateTimer = updateTimer,
            };
        }
        public void LoadFromSerializable(LevelEngine level, SerializableAuraEffect serializable)
        {
            if (serializable == null)
                return;
            updateTimer = serializable.updateTimer ?? updateTimer;
            buffCaches.Clear();
            if (serializable.buffs != null)
            {
                foreach (var seriBuff in serializable.buffs)
                {
                    var buff = seriBuff.GetBuff(level);
                    if (buff == null || buff.Target == null)
                        continue;
                    buffCaches.Add(buff.Target, buff);
                }
            }
        }
        private Buff AddTargetBuff(IBuffTarget target)
        {
            var buff = target.NewBuff(Definition.BuffID);
            buff.IsFromAura = true;
            target.AddBuff(buff);
            buffCaches[target] = buff;
            return buff;
        }
        private Buff? GetTargetBuff(IBuffTarget entity)
        {
            if (buffCaches.TryGetValue(entity, out var buff))
                return buff;
            return null;
        }
        private void ClearBuffs()
        {
            foreach (var pair in buffCaches)
            {
                var buff = pair.Value;
                if (buff == null)
                    continue;
                buff.Remove();
            }
            buffCaches.Clear();
        }
        public int ID { get; }
        public LevelEngine Level => Source.GetLevel();
        public AuraEffectDefinition Definition { get; }
        public IAuraSource Source { get; }
        private FrameTimer updateTimer;
        private Dictionary<IBuffTarget, Buff> buffCaches = new Dictionary<IBuffTarget, Buff>();
        private List<IBuffTarget> targetsBuffer = new List<IBuffTarget>();
        private List<IBuffTarget> removeBuffBuffer = new List<IBuffTarget>(1024);
    }
}
