#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Level;

namespace PVZEngine.Auras
{
    public class AuraEffectList
    {
        public void Add(LevelEngine level, AuraEffect auraEffect)
        {
            auraEffects.Add(auraEffect);
        }
        public bool Remove(LevelEngine level, AuraEffect auraEffect)
        {
            return auraEffects.Remove(auraEffect);
        }
        public void PostAdd()
        {
            foreach (var auraEffect in auraEffects)
            {
                auraEffect.PostAdd();
            }
        }
        public void PostRemove()
        {
            foreach (var auraEffect in auraEffects)
            {
                auraEffect.PostRemove();
            }
        }
        public AuraEffect GetAt(int i)
        {
            return auraEffects[i];
        }
        public AuraEffect? Get<T>()
        {
            foreach (var aura in auraEffects)
            {
                if (aura.Definition is T)
                    return aura;
            }
            return null;
        }
        public AuraEffect? Get(AuraEffectDefinition auraDef)
        {
            foreach (var aura in auraEffects)
            {
                if (aura.Definition == auraDef)
                    return aura;
            }
            return null;
        }
        public void Update()
        {
            foreach (var aura in auraEffects)
            {
                aura.UpdateAuraInterval();
            }
        }
        public void CloneTo(AuraEffectList target)
        {
            target.auraEffects.Clear();
            for (int i = 0; i < auraEffects.Count; i++)
            {
                var aura = auraEffects[i];
                target.auraEffects.Add(aura.Clone(i));
            }
        }
        public void LoadFromSerializable(LevelEngine level, IList<SerializableAuraEffect?>? seriEffects)
        {
            if (seriEffects == null)
                return;
            foreach (var aura in auraEffects)
            {
                SerializableAuraEffect? seri = null;
                foreach (var effect in seriEffects)
                {
                    if (effect != null && effect.id == aura.ID)
                    {
                        seri = effect;
                        break;
                    }
                }
                if (seri == null)
                    continue;
                aura.LoadFromSerializable(level, seri);
            }
        }
        public int Count => auraEffects.Count;
        private List<AuraEffect> auraEffects = new List<AuraEffect>();
    }
}
