#nullable enable // autogenerated

using System;
using PVZEngine.Buffs;
using PVZEngine.Tools.Timing;

namespace PVZEngine.Auras
{
    [Serializable]
    public class SerializableAuraEffect
    {
        public int id;
        public FrameTimer? updateTimer;
        public BuffReference[]? buffs;
    }
}
