#nullable enable // autogenerated

using PVZEngine.Properties;

namespace PVZEngine.SeedPacks
{
    [PropertyRegistryRegion(PropertyRegions.recharge)]
    public static class EngineRechargeProps
    {
        public static readonly PropertyMeta<int> START_MAX_RECHARGE = new PropertyMeta<int>("startMaxRecharge");
        public static int GetStartMaxRecharge(this RechargeDefinition def)
        {
            return def.GetProperty<int>(START_MAX_RECHARGE);
        }
        public static readonly PropertyMeta<int> MAX_RECHARGE = new PropertyMeta<int>("maxRecharge");
        public static int GetMaxRecharge(this RechargeDefinition def)
        {
            return def.GetProperty<int>(MAX_RECHARGE);
        }
        public static readonly PropertyMeta<float> QUALITY = new PropertyMeta<float>("quality");
        public static float GetQuality(this RechargeDefinition def)
        {
            return def.GetProperty<float>(QUALITY);
        }
        public static readonly PropertyMeta<string> NAME = new PropertyMeta<string>("name");
        public static string? GetName(this RechargeDefinition def)
        {
            return def.GetProperty<string>(NAME);
        }
    }
}
