#nullable enable // autogenerated

using PVZEngine.Auras;

namespace PVZEngine.SeedPacks
{
    public partial class SeedPack
    {
        private void InitAuras()
        {
            auraComponent.Init(this, Definition.GetAuras());
        }
        private void UpdateAuras()
        {
            auraComponent.Update();
        }

        #region 获取
        public AuraEffect? GetAuraEffect<T>()
        {
            return auraComponent.List.Get<T>();
        }
        public AuraEffect? GetAuraEffect(AuraEffectDefinition definition)
        {
            return auraComponent.List.Get(definition);
        }
        public AuraEffect GetAuraEffectAt(int i)
        {
            return auraComponent.List.GetAt(i);
        }
        public int GetAuraEffectCount()
        {
            return auraComponent.List.Count;
        }
        #endregion

        #region 序列化
        private void WriteAurasToSerializable(SerializableSeedPack seri)
        {
            auraComponent.WriteToSerializable(seri);
        }
        private void LoadAurasFromSerializable(SerializableSeedPack seri)
        {
            auraComponent.LoadFromSerializable(seri, Level);
        }
        #endregion

        #region 属性字段
        private AuraComponent auraComponent;
        #endregion
    }
}
