#nullable enable // autogenerated

using System;
using PVZEngine.Auras;
using PVZEngine.Buffs;
using PVZEngine.Level;
using PVZEngine.Properties;

namespace PVZEngine.SeedPacks
{
    public abstract class SerializableSeedPack
    {
        public long id;
        public NamespaceID? seedID;
        public long currentBuffID;
        public SerializableBuffList? buffs;
        public SerializableModifiableProperties? properties;
        public SerializableAuraEffect?[]? auras;
    }
    [Serializable]
    public class SerializableClassicSeedPack : SerializableSeedPack
    {
    }
    [Serializable]
    public class SerializableConveyorSeedPack : SerializableSeedPack
    {
    }
}
