#nullable enable // autogenerated

using System;
using MongoDB.Bson.Serialization.Attributes;
using PVZEngine.Level;

namespace PVZEngine.Entities
{
    [Serializable]
    public class EntitySourceReference : ILevelSourceReference
    {
        private EntitySourceReference(long id, NamespaceID defID, ILevelSourceReference? parent, int faction)
        {
            this.id = id;
            this.definitionID = defID;
            this.parent = parent;
            this.faction = faction;
        }
        public EntitySourceReference(Entity entity) : this(entity.ID, entity.Definition.GetID(), entity.SpawnerReference?.Clone(), entity.Cache.Faction)
        {
        }
        public EntitySourceReference Clone()
        {
            return new EntitySourceReference(ID, DefinitionID, parent?.Clone(), faction);
        }
        public Entity? GetEntity(LevelEngine game)
        {
            return game.FindEntityByID(ID);
        }
        public override bool Equals(object obj)
        {
            if (obj is EntitySourceReference entityRef)
            {
                return ID == entityRef.ID;
            }
            return base.Equals(obj);
        }
        public override int GetHashCode()
        {
            return ID.GetHashCode();
        }
        public static bool operator ==(EntitySourceReference lhs, EntitySourceReference rhs)
        {
            if (lhs is null)
                return rhs is null;
            return lhs.Equals(rhs);
        }
        public static bool operator !=(EntitySourceReference lhs, EntitySourceReference rhs)
        {
            return !(lhs == rhs);
        }
        ILevelSourceReference ILevelSourceReference.Clone()
        {
            return Clone();
        }
        ILevelSourceTarget? ILevelSourceReference.GetTarget(LevelEngine level)
        {
            return GetEntity(level);
        }
        ILevelSourceReference? ILevelSourceReference.GetParent() => parent;
        [BsonIgnore]
        public ILevelSourceReference? SpawnerReference => parent;
        [BsonIgnore]
        public int Faction => faction;
        [BsonIgnore]
        public NamespaceID DefinitionID => definitionID;
        [BsonIgnore]
        public long ID => id;
        [BsonElement]
        private NamespaceID definitionID;
        [BsonElement]
        private ILevelSourceReference? parent;
        [BsonElement]
        private int faction = -1;
        [BsonElement]
        private long id;

    }
}