#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using PVZEngine.Modifiers;

namespace PVZEngine.Entities
{
    public sealed partial class Entity : IModifierSource, IModifierProvider
    {
        private void ReevaluateModifierCaches(bool serialization)
        {
            modifierLibrary.ClearModifierCaches(serialization);
            for (int i = 0; i < Definition.GetModifierCount(); i++)
            {
                var modifier = Definition.GetModifierAt(i);
                modifierLibrary.AddModifierCache(new ModifierSourceItem(this, modifier), serialization);
            }
        }
        private void OnModifiedPropertyNeedsUpdateCallback(IPropertyKey name, bool serialization)
        {
            OnModifiedPropertyNeedsUpdate?.Invoke(name, serialization);
        }
        #region 接口实现
        T? IModifierSource.GetProperty<T>(PropertyKey<T> name) where T : default => GetProperty<T>(name);
        IEnumerable<IPropertyKey> IModifierProvider.GetModifiedProperties()
        {
            return modifierLibrary.GetModifyPropertyKeys();
        }
        void IModifierProvider.GetModifiersForProperty(IPropertyKey name, List<ModifierSourceItem> results)
        {
            modifierLibrary.GetModifierItemsForProperty(name, results);
        }
        #endregion

        #region 事件
        public event Action<IPropertyKey, bool>? OnModifiedPropertyNeedsUpdate;
        #endregion

        #region 属性字段
        private ModifierLibrary modifierLibrary;
        #endregion
    }
}