#nullable enable // autogenerated

using System.Collections.Generic;

namespace PVZEngine.DataStructures
{
    public abstract class ListUpdaterBase<T>
    {
        public void Update(IList<T> targets, IList<T> current)
        {
            // 清空并预分配容量
            currentSet.Clear();
            if (currentSet.EnsureCapacity(current.Count) < current.Count)
                currentSet.EnsureCapacity(current.Count);

            // 填充当前集合
            for (int i = 0; i < current.Count; i++)
                currentSet.Add(current[i]);

            // 处理目标集合
            for (int i = 0; i < targets.Count; i++)
            {
                var element = targets[i];
                if (currentSet.Contains(element))
                {
                    currentSet.Remove(element); // 该元素已处理，移除
                    OnUpdate(element);
                }
                else
                {
                    OnAdd(element);
                    OnUpdate(element);
                }
            }

            // 剩余元素为待删除项
            foreach (var element in currentSet)
                OnRemove(element);
        }
        protected abstract void OnAdd(T element);
        protected abstract void OnUpdate(T element);
        protected abstract void OnRemove(T element);
        private HashSet<T> currentSet = new HashSet<T>();
    }
}
