#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Auras;
using PVZEngine.Definitions;

namespace PVZEngine.Armors
{
    public abstract class ArmorBehaviourDefinition : Definition
    {
        protected ArmorBehaviourDefinition(string nsp, string name) : base(nsp, name)
        {
        }
        public virtual void PostUpdate(Armor armor) { }
        public int GetAuraCount()
        {
            return auraDefinitions.Count;
        }
        public AuraEffectDefinition GetAuraAt(int i)
        {
            return auraDefinitions[i];
        }
        protected void AddAura(AuraEffectDefinition aura)
        {
            auraDefinitions.Add(aura);
        }
        public sealed override string GetDefinitionType() => EngineDefinitionTypes.ARMOR_BEHAVIOUR;
        private List<AuraEffectDefinition> auraDefinitions = new List<AuraEffectDefinition>();
    }
}
