#nullable enable // autogenerated

using PVZEngine.Auras;

namespace PVZEngine.Armors
{
    public partial class Armor
    {
        private void InitAuras()
        {
            auraComponent.Init(this, Definition.GetAuras());
        }
        private void UpdateAuras()
        {
            auraComponent.Update();
        }

        #region 获取
        public AuraEffect GetAuraEffect<T>() where T : AuraEffectDefinition
        {
            return auraComponent.List.Get<T>();
        }
        public AuraEffect[] GetAuraEffects()
        {
            return auraComponent.List.GetAll();
        }
        #endregion

        #region 序列化
        private void WriteAurasToSerializable(SerializableArmor seri)
        {
            auraComponent.WriteToSerializable(seri);
        }
        private void LoadAurasFromSerializable(SerializableArmor seri)
        {
            auraComponent.LoadFromSerializable(seri, Level);
        }
        #endregion

        #region 属性字段
        private AuraComponent auraComponent;
        #endregion
    }
}