#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Auras;
using PVZEngine.Tools;

namespace PVZEngine.Armors
{
    public partial class Armor
    {
        private void InitAuras()
        {
            using var aurasItem = ListPool<AuraEffectDefinition>.Rent();
            var auras = aurasItem.Value;
            for (int i = 0; i < Definition.GetBehaviourCount(); i++)
            {
                var behaviour = Definition.GetBehaviourAt(i);
                for (int a = 0; a < behaviour.GetAuraCount(); a++)
                {
                    var aura = behaviour.GetAuraAt(a);
                    auras.Add(aura);
                }
            }
            auraComponent.Init(this, auras);
        }
        private void UpdateAuras()
        {
            auraComponent.Update();
        }

        #region 获取
        public AuraEffect? GetAuraEffect<T>()
        {
            return auraComponent.List.Get<T>();
        }
        public AuraEffect? GetAuraEffect(AuraEffectDefinition definition)
        {
            return auraComponent.List.Get(definition);
        }
        public AuraEffect GetAuraEffectAt(int i)
        {
            return auraComponent.List.GetAt(i);
        }
        public int GetAuraEffectCount()
        {
            return auraComponent.List.Count;
        }
        #endregion

        #region 序列化
        private void WriteAurasToSerializable(SerializableArmor seri)
        {
            auraComponent.WriteToSerializable(seri);
        }
        private void LoadAurasFromSerializable(SerializableArmor seri)
        {
            auraComponent.LoadFromSerializable(seri, Level);
        }
        #endregion

        #region 属性字段
        private AuraComponent auraComponent;
        #endregion
    }
}