#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Level;
using PVZEngine.Shells;

namespace PVZEngine.Armors
{
    public static class EngineArmorExt
    {
        public static ShellDefinition? GetShellDefinition(this Armor armor)
        {
            var shellID = armor.GetShellID();
            if (shellID == null)
                return null;
            return armor.Level.Content.GetShellDefinition(shellID);
        }
        public static NamespaceID GetModelKeyOfArmorSlot(NamespaceID slot)
        {
            if (!armorSlotModelKeys.TryGetValue(slot, out var key))
            {
                key = new NamespaceID(slot.SpaceName, $"armor.{slot.Path}");
                armorSlotModelKeys.Add(slot, key);
            }
            return key;
        }
        private static readonly Dictionary<NamespaceID, NamespaceID> armorSlotModelKeys = new Dictionary<NamespaceID, NamespaceID>();
    }
}
