#nullable enable // autogenerated

using System;
using PVZEngine.Auras;
using PVZEngine.Buffs;
using PVZEngine.Properties;

namespace PVZEngine.Armors
{
    [Serializable]
    public class SerializableArmor : IHasSerializableAuras
    {
        public NamespaceID? definitionID;
        public float health;
        public NamespaceID? slot;
        [Obsolete]
        public long currentBuffID;
        public SerializableBuffList? buffs;
        public SerializableModifiableProperties? properties;
        public SerializableAuraEffect?[]? auras;

        public SerializableAuraEffect?[]? GetSerializableAuras() => auras;
        public void SetSerializableAuras(SerializableAuraEffect?[]? auras) => this.auras = auras;
    }
}
