#nullable enable // autogenerated

using System.Collections.Generic;
using System.Linq;

namespace PVZEngine.Modifiers
{
    public abstract class ArrayModifierCalculator<T> : ModifierCalculator<T[], ArrayModifier<T[]>>
    {
        public override T[]? CalculateGeneric(T[]? value, IEnumerable<ModifierSourceItem> modifiers)
        {
            if (modifiers.Count() == 0)
                return value;

            IEnumerable<T>? enumerableValue = value;
            var grouped = modifiers.GroupBy(m => m.modifier?.Priority ?? 0).OrderBy(g => g.Key);
            foreach (var layerModifiers in grouped)
            {
                IEnumerable<T>? replaceValue = enumerableValue;
                IEnumerable<T>? appendValue = null;
                IEnumerable<T>? prependValue = null;
                IEnumerable<T>? intersectValue = null;
                IEnumerable<T>? unionValue = null;
                IEnumerable<T>? exceptValue = null;
                foreach (var modi in layerModifiers)
                {
                    var buff = modi.container;
                    if (modi.modifier is not ArrayModifier<T[]> modifier)
                        continue;
                    var modifierValue = modifier.GetModifierValueGeneric(buff);
                    if (!modifier.FitsConditionGeneric(modifierValue))
                        continue;
                    switch (modifier.Operator)
                    {
                        case ArrayOperator.Replace:
                            replaceValue = modifierValue;
                            break;
                        case ArrayOperator.Append:
                            if (modifierValue == null)
                                break;
                            if (appendValue == null)
                            {
                                appendValue = modifierValue;
                            }
                            else
                            {
                                appendValue = appendValue.Concat(modifierValue);
                            }
                            break;
                        case ArrayOperator.Prepend:
                            if (modifierValue == null)
                                break;
                            if (prependValue == null)
                            {
                                prependValue = modifierValue;
                            }
                            else
                            {
                                prependValue = modifierValue.Concat(prependValue);
                            }
                            break;
                        case ArrayOperator.Intersect:
                            if (modifierValue == null)
                                break;
                            if (intersectValue == null)
                            {
                                intersectValue = modifierValue;
                            }
                            else
                            {
                                intersectValue = intersectValue.Intersect(modifierValue);
                            }
                            break;
                        case ArrayOperator.Union:
                            if (modifierValue == null)
                                break;
                            if (unionValue == null)
                            {
                                unionValue = modifierValue;
                            }
                            else
                            {
                                unionValue = unionValue.Union(modifierValue);
                            }
                            break;
                        case ArrayOperator.Except:
                            if (modifierValue == null)
                                break;
                            if (exceptValue == null)
                            {
                                exceptValue = modifierValue;
                            }
                            else
                            {
                                exceptValue = exceptValue.Union(modifierValue);
                            }
                            break;
                    }
                }
                enumerableValue = replaceValue;
                enumerableValue = Concat(enumerableValue, appendValue);
                enumerableValue = Concat(prependValue, enumerableValue);
                enumerableValue = Intersect(enumerableValue, intersectValue);
                enumerableValue = Union(enumerableValue, unionValue);
                enumerableValue = Except(enumerableValue, exceptValue);
            }
            return enumerableValue?.ToArray();
        }
        public static IEnumerable<T>? Concat(IEnumerable<T>? value, IEnumerable<T>? operand)
        {
            if (operand == null)
                return value;
            if (value == null)
                return operand;
            return value.Concat(operand);
        }
        public static IEnumerable<T>? Intersect(IEnumerable<T>? value, IEnumerable<T>? operand)
        {
            if (operand == null)
                return value;
            if (value == null)
                return null;
            return value.Intersect(operand);
        }
        public static IEnumerable<T>? Union(IEnumerable<T>? value, IEnumerable<T>? operand)
        {
            if (operand == null)
                return value;
            if (value == null)
                return operand;
            return value.Union(operand);
        }
        public static IEnumerable<T>? Except(IEnumerable<T>? value, IEnumerable<T>? operand)
        {
            if (operand == null)
                return value;
            if (value == null)
                return null;
            return value.Except(operand);
        }
    }
    public class NamespaceIDArrayCalculator : ArrayModifierCalculator<NamespaceID>
    {
    }
}
