#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Tools;

namespace PVZEngine.Modifiers
{
    public abstract class ArrayModifierCalculator<T> : ModifierCalculator<T[], ArrayModifier<T[]>>
    {
        public override T[]? CalculateGeneric(T[]? value, IList<ModifierSourceItem> modifiers)
        {
            if (modifiers.Count == 0)
                return value;

            bool resultIsNull = value == null;
            finalResult.Clear();

            using var groupedItem = GroupPool<int, ModifierSourceItem>.Rent();
            var grouped = groupedItem.Value;
            foreach (var modifierItem in modifiers)
            {
                var priority = modifierItem.modifier.Priority;
                grouped.Add(priority, modifierItem);
            }
            grouped.Sort();

            foreach (var layerModifiers in grouped)
            {
                nothingToIntersect = true;
                replaceValue.Clear();
                appendValue.Clear();
                prependValue.Clear();
                intersectValue.Clear();
                unionValue.Clear();
                exceptValue.Clear();
                replaceValue.AddRange(finalResult);
                foreach (var modi in layerModifiers)
                {
                    var buff = modi.container;
                    if (modi.modifier is not ArrayModifier<T[]> modifier)
                        continue;
                    var modifierValue = modifier.GetModifierValueGeneric(buff);
                    if (!modifier.FitsConditionGeneric(modifierValue))
                        continue;
                    switch (modifier.Operator)
                    {
                        case ArrayOperator.Replace:
                            if (modifierValue == null)
                            {
                                resultIsNull = true;
                                replaceValue.Clear();
                            }
                            else
                            {
                                resultIsNull = false;
                                replaceValue.Clear();
                                replaceValue.AddRange(modifierValue);
                            }
                            break;
                        case ArrayOperator.Append:
                            appendValue.AppendList(modifierValue);
                            break;
                        case ArrayOperator.Prepend:
                            prependValue.PrependList(modifierValue);
                            break;
                        case ArrayOperator.Intersect:
                            if (modifierValue == null)
                                break;
                            if (nothingToIntersect)
                            {
                                nothingToIntersect = false;
                                intersectValue.Clear();
                                intersectValue.AddRange(modifierValue);
                            }
                            else
                            {
                                intersectValue.IntersectList(modifierValue);
                            }
                            break;
                        case ArrayOperator.Union:
                            unionValue.UnionList(modifierValue);
                            break;
                        case ArrayOperator.Except:
                            exceptValue.UnionList(modifierValue);
                            break;
                    }
                }
                finalResult.Clear();
                if (replaceValue.Count > 0)
                {
                    finalResult.AddRange(replaceValue);
                    resultIsNull = false;
                }
                if (appendValue.Count > 0)
                {
                    finalResult.AppendList(appendValue);
                    resultIsNull = false;
                }
                if (prependValue.Count > 0)
                {
                    finalResult.PrependList(prependValue);
                    resultIsNull = false;
                }
                if (!nothingToIntersect)
                {
                    finalResult.IntersectList(intersectValue);
                }
                if (unionValue.Count > 0)
                {
                    finalResult.UnionList(unionValue);
                    resultIsNull = false;
                }
                if (exceptValue.Count > 0)
                {
                    finalResult.ExceptList(exceptValue);
                }
            }
            return resultIsNull ? null : finalResult.ToArray();
        }
        private bool nothingToIntersect = true;
        private List<T> finalResult = new List<T>();
        private List<T> replaceValue = new List<T>();
        private List<T> appendValue = new List<T>();
        private List<T> prependValue = new List<T>();
        private List<T> intersectValue = new List<T>();
        private List<T> unionValue = new List<T>();
        private List<T> exceptValue = new List<T>();
    }
    public class NamespaceIDArrayCalculator : ArrayModifierCalculator<NamespaceID>
    {
    }
}
