#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Tools;

namespace PVZEngine.Modifiers
{
    public class BooleanCalculator : ModifierCalculator<bool, BooleanModifier>
    {
        public override bool CalculateGeneric(bool value, IList<ModifierSourceItem> modifiers)
        {
            if (modifiers.Count == 0)
                return value;

            using var groupedItem = GroupPool<int, ModifierSourceItem>.Rent();
            var grouped = groupedItem.Value;
            foreach (var modifierItem in modifiers)
            {
                var priority = modifierItem.modifier.Priority;
                grouped.Add(priority, modifierItem);
            }
            grouped.Sort();

            foreach (var layerModifiers in grouped)
            {
                bool setValue = value;
                bool orValue = false;
                bool xorValue = false;
                bool andValue = true;
                bool reverse = false;
                foreach (var modi in layerModifiers)
                {
                    var buff = modi.container;
                    if (modi.modifier is not BooleanModifier modifier)
                        continue;
                    var modifierValue = modifier.GetModifierValueGeneric(buff);
                    if (!modifier.FitsConditionGeneric(modifierValue))
                        continue;
                    switch (modifier.Operator)
                    {
                        case BooleanOperator.Set:
                            setValue = modifierValue;
                            break;
                        case BooleanOperator.SetNot:
                            setValue = !modifierValue;
                            break;
                        case BooleanOperator.Not:
                            reverse = !reverse;
                            break;
                        case BooleanOperator.Or:
                            orValue |= modifierValue;
                            break;
                        case BooleanOperator.Xor:
                            xorValue ^= modifierValue;
                            break;
                        case BooleanOperator.And:
                            andValue &= modifierValue;
                            break;
                    }
                }
                value = setValue;
                value |= orValue;
                value ^= xorValue;
                value &= andValue;
                if (reverse)
                {
                    value = !value;
                }
            }
            return value;
        }
    }
}
