#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Tools;

namespace PVZEngine.Modifiers
{
    public abstract class SetModifierCalculator<T> : ModifierCalculator<T, SetModifier<T>>
    {
        public override T? CalculateGeneric(T? value, IList<ModifierSourceItem> modifiers)
        {
            if (modifiers.Count == 0)
                return value;

            using var orderedBufferItem = ListPool<ModifierSourceItem>.Rent();
            var orderedBuffer = orderedBufferItem.Value;
            foreach (var modifierItem in modifiers)
            {
                if (modifierItem.modifier is not SetModifier<T>)
                    continue;
                orderedBuffer.Add(modifierItem);
            }
            orderedBuffer.Sort(ModifierSourceItemComparer.Descending);

            foreach (var modifierContainer in orderedBuffer)
            {
                var modifier = (SetModifier<T>)modifierContainer.modifier;
                var container = modifierContainer.container;
                var modifierValue = modifier.GetModifierValueGeneric(container);
                if (!modifier.FitsConditionGeneric(modifierValue))
                    continue;
                if (modifier.Operator == SetOperator.SetIfNotNull && modifierValue == null)
                    continue;
                return modifierValue;
            }
            return value;
        }
    }
    public class NamespaceIDCalculator : SetModifierCalculator<NamespaceID>
    {
    }
    public class StringCalculator : SetModifierCalculator<string>
    {
    }
}
