#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Entities;

namespace PVZEngine.Grids
{
    public partial class LawnGrid
    {
        #region 添加占据实体
        private HashSet<Entity> GetOrCreateLayerEntityHashSet(NamespaceID layer)
        {
            if (!layerEntities.TryGetValue(layer, out var hashSet))
            {
                hashSet = new HashSet<Entity>();
                layerEntities.Add(layer, hashSet);
            }
            return hashSet;
        }
        private void AddReversedLayerEntity(NamespaceID layer, Entity entity)
        {
            if (reverseLayerEntities.TryGetValue(entity, out var layerHashSet))
            {
                layerHashSet.Add(layer);
            }
            else
            {
                layerHashSet = new HashSet<NamespaceID>() { layer };
                reverseLayerEntities.Add(entity, layerHashSet);
            }
        }
        public void AddLayerEntity(NamespaceID layer, Entity entity)
        {
            var hashSet = GetOrCreateLayerEntityHashSet(layer);
            hashSet.Add(entity);
            AddReversedLayerEntity(layer, entity);
        }
        #endregion

        #region 移除占据实体
        public void RemoveLayerEntity(NamespaceID layer, Entity entity)
        {
            if (layerEntities.TryGetValue(layer, out var hashSet))
            {
                hashSet.Remove(entity);
                if (hashSet.Count <= 0)
                {
                    layerEntities.Remove(layer);
                }
            }
            if (reverseLayerEntities.TryGetValue(entity, out var reverseHashSet))
            {
                reverseHashSet.Remove(layer);
                if (reverseHashSet.Count <= 0)
                {
                    reverseLayerEntities.Remove(entity);
                }
            }
        }
        public void RemoveGridEntity(Entity entity)
        {
            if (reverseLayerEntities.TryGetValue(entity, out var reversedHashSet))
            {
                foreach (var layer in reversedHashSet)
                {
                    if (layerEntities.TryGetValue(layer, out var hashSet))
                    {
                        hashSet.Remove(entity);
                        if (hashSet.Count <= 0)
                        {
                            layerEntities.Remove(layer);
                        }
                    }
                }
                reversedHashSet.Clear();
                reverseLayerEntities.Remove(entity);
            }
        }
        #endregion

        #region 获取占据实体
        public Entity? GetLayerEntity(NamespaceID layer)
        {
            if (layerEntities.TryGetValue(layer, out var hashSet))
            {
                foreach (var ent in hashSet)
                {
                    return ent;
                }
            }
            return null;
        }
        public void GetLayerEntities(NamespaceID layer, List<Entity> results)
        {
            if (layerEntities.TryGetValue(layer, out var hashSet))
            {
                results.AddRange(hashSet);
            }
        }
        public bool IsEntityOnLayer(Entity entity, NamespaceID layer)
        {
            if (layerEntities.TryGetValue(layer, out var hashSet))
            {
                return hashSet.Contains(entity);
            }
            return false;
        }
        public bool HasEntity(Entity entity)
        {
            return reverseLayerEntities.ContainsKey(entity);
        }
        public bool IsEmpty()
        {
            return layerEntities.Count == 0;
        }
        public void GetEntities(List<Entity> results)
        {
            results.AddRange(reverseLayerEntities.Keys);
        }
        public void GetLayers(List<NamespaceID> results)
        {
            results.AddRange(layerEntities.Keys);
        }
        #endregion

        #region 获取实体占据层
        public void GetEntityLayersNonAlloc(Entity entity, List<NamespaceID> results)
        {
            if (reverseLayerEntities.TryGetValue(entity, out var reverseHashSet))
            {
                results.AddRange(reverseHashSet);
            }
        }
        #endregion

        #region 序列化
        private void WriteLayersToSerializable(SerializableGrid seri)
        {
            seri.layerEntityLists = new Dictionary<string, long[]>();
            foreach (var pair in layerEntities)
            {
                var entities = new long[pair.Value.Count];
                int index = 0;
                foreach (var ent in pair.Value)
                {
                    entities[index] = ent.ID;
                    index++;
                }
                seri.layerEntityLists.Add(pair.Key.ToString(), entities);
            }
        }
        private void LoadLayersFromSerializable(SerializableGrid seri)
        {
            layerEntities.Clear();
            reverseLayerEntities.Clear();
#pragma warning disable CS0612 // 类型或成员已过时
            if (seri.layerEntityLists != null)
            {
                foreach (var pair in seri.layerEntityLists)
                {
                    var layer = NamespaceID.ParseStrict(pair.Key);
                    var entityHashSet = new HashSet<Entity>();
                    foreach (var entityID in pair.Value)
                    {
                        var entity = Level.FindEntityByID(entityID);
                        if (entity == null)
                            continue;

                        entityHashSet.Add(entity);
                        AddReversedLayerEntity(layer, entity);
                    }
                    layerEntities.Add(layer, entityHashSet);
                }
            }
            else if (seri.layerEntities != null)
            {
                foreach (var pair in seri.layerEntities)
                {
                    var layer = NamespaceID.ParseStrict(pair.Key);
                    var entity = Level.FindEntityByID(pair.Value);
                    if (entity == null)
                        continue;

                    var layerHashSet = new HashSet<NamespaceID>() { layer };
                    var entityHashSet = new HashSet<Entity>() { entity };
                    layerEntities.Add(layer, entityHashSet);
                    reverseLayerEntities.Add(entity, layerHashSet);
                }
            }
#pragma warning restore CS0612 // 类型或成员已过时
        }
        #endregion

        #region 属性
        private Dictionary<NamespaceID, HashSet<Entity>> layerEntities = new Dictionary<NamespaceID, HashSet<Entity>>();
        private Dictionary<Entity, HashSet<NamespaceID>> reverseLayerEntities = new Dictionary<Entity, HashSet<NamespaceID>>();
        #endregion 属性
    }
}