#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using PVZEngine.Tools;

namespace PVZEngine
{
    public sealed class PropertyKeyString
    {
        public string propertyKey;

        private PropertyKeyString(string propertyKey)
        {
            this.propertyKey = propertyKey;
        }

        public override bool Equals(object obj)
        {
            return obj is PropertyKeyString key &&
                   propertyKey == key.propertyKey;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(propertyKey);
        }
        public static bool IsValid(PropertyKeyString key)
        {
            return !string.IsNullOrEmpty(key.propertyKey);
        }
        public static bool operator ==(PropertyKeyString lhs, PropertyKeyString rhs)
        {
            return lhs.propertyKey == rhs.propertyKey;
        }
        public static bool operator !=(PropertyKeyString lhs, PropertyKeyString rhs)
        {
            return lhs.propertyKey != rhs.propertyKey;
        }
        public static implicit operator PropertyKeyString(string key)
        {
            return GetOrCreate(key);
        }
        public static implicit operator string(PropertyKeyString meta)
        {
            return meta.propertyKey;
        }
        public static PropertyKeyString GetOrCreate(string key)
        {
            return WeakLookupCache<string, PropertyKeyString>.GetOrCreate(key, s => new PropertyKeyString(s));
        }
    }
    public class PropertyKeyStringComparer : IEqualityComparer<PropertyKeyString>
    {
        public bool Equals(PropertyKeyString x, PropertyKeyString y)
        {
            if (ReferenceEquals(x, y))
                return true;
            if (x is null || y is null)
                return false;
            return x.propertyKey == y.propertyKey; // 直接比较 int Key
        }

        public int GetHashCode(PropertyKeyString obj)
        {
            return obj.propertyKey.GetHashCode(); // 直接使用 int 的哈希码
        }
    }
}
