#nullable enable // autogenerated

using System;
using UnityEngine;

namespace PVZEngine
{
    [Serializable]
    public class NamespaceIDReference
    {
        public NamespaceID Get()
        {
            if (cache == null || !Compare(cache))
            {
                cache = new NamespaceID(spacename, path);
            }
            return cache;
        }
        public bool Compare(NamespaceID id)
        {
            return id.SpaceName == spacename && id.Path == path;
        }
        [SerializeField]
        private string spacename = null!;
        [SerializeField]
        private string path = null!;
        private NamespaceID? cache;
    }
}
