#nullable enable // autogenerated

using System;
using System.Collections.Generic;

namespace PVZEngine.Tools
{
    public static class LinqHelper
    {
        public static void TakeWhileLast<T>(this IList<T> list, Func<T, bool> predicate, List<T> results)
        {
            for (int i = list.Count - 1; i >= 0; i--)
            {
                var element = list[i];
                if (predicate(element))
                {
                    results.Insert(0, element);
                }
                else
                {
                    break;
                }
            }
        }

        #region 极端值（单个）
        public static float GetMostOne(this IEnumerable<float> targets)
        {
            return GetExtremeOne(targets, v => v, comparer: static (current, max) => current > max, initialValue: float.MinValue);
        }
        public static float GetLeastOne(this IEnumerable<float> targets)
        {
            return GetExtremeOne(targets, v => v, comparer: static (current, max) => current < max, initialValue: float.MaxValue);
        }
        public static T? GetMostOne<T>(this IEnumerable<T> targets, Func<T, float> selector)
        {
            return GetExtremeOne(targets, selector, comparer: static (current, max) => current > max, initialValue: float.MinValue);
        }
        public static T? GetLeastOne<T>(this IEnumerable<T> targets, Func<T, float> selector)
        {
            return GetExtremeOne(targets, selector, comparer: static (current, max) => current < max, initialValue: float.MaxValue);
        }
        private static T? GetExtremeOne<T>(IEnumerable<T> targets, Func<T, float> selector, Func<float, float, bool> comparer, float initialValue)
        {
            float extremeValue = initialValue;
            T? extremeItem = default;

            foreach (var item in targets)
            {
                float value = selector(item);
                if (comparer(value, extremeValue))
                {
                    extremeValue = value;
                    extremeItem = item;
                }
            }
            return extremeItem;
        }
        #endregion

        #region 极端值（多个）
        public static void GetMostOnes(this IEnumerable<float> targets, List<float> results)
        {
            GetExtremeOnes(targets, v => v, comparer: static (current, max) => current > max, initialValue: float.MinValue, results);
        }
        public static void GetLeastOnes(this IEnumerable<float> targets, List<float> results)
        {
            GetExtremeOnes(targets, v => v, comparer: static (current, max) => current < max, initialValue: float.MaxValue, results);
        }
        public static void GetMostOnes<T>(this IEnumerable<T> targets, Func<T, float> selector, List<T> results)
        {
            GetExtremeOnes(targets, selector, comparer: static (current, max) => current > max, initialValue: float.MinValue, results);
        }
        public static void GetLeastOnes<T>(this IEnumerable<T> targets, Func<T, float> selector, List<T> results)
        {
            GetExtremeOnes(targets, selector, comparer: static (current, max) => current < max, initialValue: float.MaxValue, results);
        }
        private static void GetExtremeOnes<T>(IEnumerable<T> targets, Func<T, float> selector, Func<float, float, bool> comparer, float initialValue, List<T> results)
        {
            float extremeValue = initialValue;

            foreach (var item in targets)
            {
                float value = selector(item);
                if (comparer(value, extremeValue))
                {
                    extremeValue = value;
                    results.Clear();
                    results.Add(item);
                }
                else if (value == extremeValue)
                {
                    results.Add(item);
                }
            }
        }
        #endregion
    }
}
