#nullable enable // autogenerated

using System.Collections.Generic;

namespace PVZEngine.Tools
{
    public static class ListHelper
    {
        public static void TakeToList<T>(this IList<T> list, int count, List<T> results)
        {
            if (count == 0)
                return;
            for (int i = 0; i < count; i++)
            {
                if (i >= list.Count)
                    return;
                results.Add(list[i]);
            }
        }
        public static void FillRange(this List<int> list, int min, int max)
        {
            for (int i = min; i < max; i++)
            {
                list.Add(i);
            }
        }
        public static void AppendList<T>(this List<T> list, IList<T>? operand)
        {
            if (operand == null)
                return;
            list.AddRange(operand);
        }
        public static void PrependList<T>(this List<T> list, IList<T>? other)
        {
            if (other == null)
                return;
            foreach (var prependItem in other)
            {
                list.Insert(0, prependItem);
            }
        }
        public static void IntersectList<T>(this List<T> list, IList<T>? other)
        {
            if (other == null)
                return;
            if (list.Count == 0 || other.Count == 0)
            {
                list.Clear();
                return;
            }

            using var intersectBufferItem = ListPool<int>.Rent();
            var removeBuffer = intersectBufferItem.Value;

            for (int i = list.Count - 1; i >= 0; i--)
            {
                var item = list[i];
                if (!other.Contains(item))
                {
                    removeBuffer.Add(i);
                }
            }
            foreach (var index in removeBuffer)
            {
                list.RemoveAt(index);
            }
        }
        public static void UnionList<T>(this List<T> list, IList<T>? other)
        {
            if (other == null)
                return;
            if (other.Count == 0)
            {
                return;
            }
            foreach (var item in other)
            {
                if (!list.Contains(item))
                {
                    list.Add(item);
                }
            }
        }
        public static void ExceptList<T>(this List<T> list, IList<T>? other)
        {
            if (other == null)
                return;
            if (other.Count == 0)
            {
                return;
            }

            using var exceptBufferItem = ListPool<int>.Rent();
            var removeBuffer = exceptBufferItem.Value;

            for (int i = list.Count - 1; i >= 0; i--)
            {
                var item = list[i];
                if (other.Contains(item))
                {
                    removeBuffer.Add(i);
                }
            }
            foreach (var index in removeBuffer)
            {
                list.RemoveAt(index);
            }
        }
    }
}
