#nullable enable // autogenerated

using PVZEngine.Tools.Cloning;

namespace PVZEngine.Level
{
    public interface ILevelSourceReference : ICanClone
    {
        object ICanClone.Clone() => CloneReference();
        ILevelSourceReference CloneReference();
        ILevelSourceTarget? GetTarget(LevelEngine level);
        ILevelSourceReference? GetParent();
    }
    public interface ILevelSourceTarget
    {
    }
}
