#nullable enable // autogenerated

namespace PVZEngine.Level
{
    public interface ILevelSourceReference
    {
        ILevelSourceReference Clone();
        ILevelSourceTarget? GetTarget(LevelEngine level);
        ILevelSourceReference? GetParent();
    }
    public interface ILevelSourceTarget
    {
    }
}
