#nullable enable // autogenerated

using PVZEngine;
using PVZEngine.Definitions;

namespace PVZEngine.Difficulties
{
    public class DifficultyDefinition : Definition
    {
        public DifficultyDefinition(string nsp, string name) : base(nsp, name)
        {
        }
        public sealed override string GetDefinitionType() => EngineDefinitionTypes.DIFFICULTY;
    }
}
