#nullable enable // autogenerated

using System;
using PVZEngine.Armors;
using PVZEngine.Level;
using PVZEngine.Shells;
using UnityEngine;

namespace PVZEngine.Damages
{
    public class ArmorDamageOutputPart : DamageOutputPart
    {
        public ArmorDamageOutputPart(ArmorDamageInputPart input, ShellDefinition? shell) : base(input, shell)
        {
            Armor = input.Armor;
        }
        public ArmorDamageOutputPart(LevelEngine level, SerializableArmorDamageResult seri) : base(level, seri)
        {
            var armor = Entity.GetArmorAtSlot(seri.armorSlot);
            if (armor == null)
            {
                throw new NullReferenceException($"Cannot find the armor on slot {seri.armorSlot} on entity {Entity} while loading SerializableArmorDamageResult.");
            }
            Armor = armor;
        }

        public override Vector3 GetPosition()
        {
            return Entity.Position;
        }
        public override SerializableDamageOutputPart ToSerializable()
        {
            return new SerializableArmorDamageResult(this);
        }
        public Armor Armor { get; set; }
    }
    [Serializable]
    public class SerializableArmorDamageResult : SerializableDamageOutputPart
    {
        public SerializableArmorDamageResult(ArmorDamageOutputPart result) : base(result)
        {
            this.armorSlot = result.Armor.Slot;
        }
        public override DamageOutputPart ToDeserialized(LevelEngine level)
        {
            return new ArmorDamageOutputPart(level, this);
        }
        public NamespaceID armorSlot;
    }
}
