#nullable enable // autogenerated

using System;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.Shells;
using UnityEngine;

namespace PVZEngine.Damages
{
    public class BodyDamageOutputPart : DamageOutputPart
    {
        public BodyDamageOutputPart(BodyDamageInputPart input, ShellDefinition? shell) : base(input, shell)
        {
        }
        public BodyDamageOutputPart(LevelEngine level, SerializableBodyDamageResult seri) : base(level, seri)
        {
        }
        public override SerializableDamageOutputPart ToSerializable()
        {
            return new SerializableBodyDamageResult(this);
        }
        public override Vector3 GetPosition()
        {
            return Entity.Position;
        }
    }
    [Serializable]
    public class SerializableBodyDamageResult : SerializableDamageOutputPart
    {
        public SerializableBodyDamageResult(BodyDamageOutputPart result) : base(result)
        {
        }
        public override DamageOutputPart ToDeserialized(LevelEngine level)
        {
            return new BodyDamageOutputPart(level, this);
        }
    }
}
