#nullable enable // autogenerated

using System;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.Shells;
using UnityEngine;

namespace PVZEngine.Damages
{
    public abstract class DamageOutputPart
    {
        public DamageOutputPart(DamageInputPart input, ShellDefinition? shell)
        {
            values = new DamageOutputPartValues(input.Amount, 0, 0);
            Entity = input.Entity;
            Effects = input.Effects;
            Source = input.Source;
            ShellDefinition = shell;
        }
        public DamageOutputPart(LevelEngine level, SerializableDamageOutputPart seri)
        {
            var ent = level.FindEntityByID(seri.entityID);
            if (ent == null)
            {
                throw new NullReferenceException($"Cannot find the entity with id {seri.entityID} while loading SerializableDamageResult.");
            }
            Entity = ent;
            Source = seri.source;
            Effects = new DamageEffectList(seri.effects);
            values = seri.values;
            Fatal = seri.fatal;
            ShellDefinition = level.Content.GetShellDefinition(seri.shellID);
        }
        public abstract Vector3 GetPosition();
        public bool HasEffect(NamespaceID effect)
        {
            return Effects?.HasEffect(effect) ?? false;
        }
        public bool HasDamageAmount()
        {
            return Amount > 0;
        }
        public void SetDamageAmount(float amount, float effective, float overflow)
        {
            values.amount = amount;
            values.effectiveAmount = effective;
            values.overflowAmount = overflow;
        }
        public abstract SerializableDamageOutputPart ToSerializable();
        public DamageOutputPartValues GetValues() => values;

        private DamageOutputPartValues values;
        public ILevelSourceReference? Source { get; set; }
        public DamageEffectList Effects { get; set; }
        public ShellDefinition? ShellDefinition { get; set; }
        public bool Fatal { get; set; }
        public Entity Entity { get; set; }
        public float Amount
        {
            get => values.amount;
        }
        public float EffectiveAmount
        {
            get => values.effectiveAmount;
        }
        public float OverflowAmount
        {
            get => values.overflowAmount;
        }
    }
    [Serializable]
    public abstract class SerializableDamageOutputPart
    {
        public ILevelSourceReference? source;
        public NamespaceID[] effects;
        public NamespaceID? shellID;
        public long entityID;
        public bool fatal;
        public DamageOutputPartValues values;

        protected SerializableDamageOutputPart(DamageOutputPart result)
        {
            source = result.Source;
            effects = result.Effects.GetEffects();
            fatal = result.Fatal;
            shellID = result.ShellDefinition?.GetID();
            entityID = result.Entity.ID;
            values = result.GetValues();
        }
        public abstract DamageOutputPart ToDeserialized(LevelEngine level);
    }
}
