#nullable enable // autogenerated

using System.Collections.Generic;
using PVZEngine.Entities;

namespace PVZEngine.Damages
{
    public class DamageOutput
    {
        public DamageOutput(Entity entity)
        {
            Entity = entity;
        }

        public Entity Entity { get; set; }
        public BodyDamageOutputPart? BodyResult { get; set; }
        public ArmorDamageOutputPart? ArmorResult { get; set; }
        public ArmorDamageOutputPart? ShieldResult { get; set; }
        public NamespaceID? ShieldTarget { get; set; }
        public bool HasDamageAmount()
        {
            if (ArmorResult != null && ArmorResult.HasDamageAmount())
                return true;
            if (BodyResult != null && BodyResult.HasDamageAmount())
                return true;
            if (ShieldResult != null && ShieldResult.HasDamageAmount())
                return true;
            return false;
        }
        public bool HasAnyNotFatal()
        {
            if (ArmorResult != null && !ArmorResult.Fatal)
                return true;
            if (BodyResult != null && !BodyResult.Fatal)
                return true;
            if (ShieldResult != null && !ShieldResult.Fatal)
                return true;
            return false;
        }
        public bool HasAnyFatal()
        {
            if (ArmorResult != null && ArmorResult.Fatal)
                return true;
            if (BodyResult != null && BodyResult.Fatal)
                return true;
            if (ShieldResult != null && ShieldResult.Fatal)
                return true;
            return false;
        }
        public float GetTotalAmount()
        {
            float sum = 0;
            if (ArmorResult != null)
                sum += ArmorResult.Amount;
            if (BodyResult != null)
                sum += BodyResult.Amount;
            if (ShieldResult != null)
                sum += ShieldResult.Amount;
            return sum;
        }
        public float GetTotalEffectiveAmount()
        {
            float sum = 0;
            if (ArmorResult != null)
                sum += ArmorResult.EffectiveAmount;
            if (BodyResult != null)
                sum += BodyResult.EffectiveAmount;
            if (ShieldResult != null)
                sum += ShieldResult.EffectiveAmount;
            return sum;
        }
        public float GetTotalOverflowAmount()
        {
            float sum = 0;
            if (ArmorResult != null)
                sum += ArmorResult.OverflowAmount;
            if (BodyResult != null)
                sum += BodyResult.OverflowAmount;
            if (ShieldResult != null)
                sum += ShieldResult.OverflowAmount;
            return sum;
        }
        public float GetFinalOverflowAmount()
        {
            if (BodyResult != null)
                return BodyResult.OverflowAmount;
            if (ArmorResult != null)
                return ArmorResult.OverflowAmount;
            if (ShieldResult != null)
                return ShieldResult.OverflowAmount;
            return 0;
        }
        public DamageOutputPart[] GetAllResults()
        {
            List<DamageOutputPart> results = new List<DamageOutputPart>();
            if (ArmorResult != null) results.Add(ArmorResult);
            if (BodyResult != null) results.Add(BodyResult);
            if (ShieldResult != null) results.Add(ShieldResult);
            return results.ToArray();
        }
    }
}
