#nullable enable // autogenerated


namespace PVZEngine.Damages
{
    public class DamageEffectList
    {
        public DamageEffectList(params NamespaceID[] effects)
        {
            this.effects = effects;
        }
        public NamespaceID[] GetEffects()
        {
            return effects;
        }
        public bool HasEffect(NamespaceID effect)
        {
            foreach (var effectID in effects)
            {
                if (effectID == effect)
                    return true;
            }
            return false;
        }
        private NamespaceID[] effects;
    }
}
