#nullable enable // autogenerated

using System;

namespace PVZEngine.Damages
{
    [Serializable]
    public class DamageOutputPartValues
    {
        public float amount;
        [Obsolete]
        public float spendAmount;
        public float overflowAmount;
        public float effectiveAmount;

        public DamageOutputPartValues(float amount, float overflowAmount, float effectiveAmount)
        {
            this.amount = amount;
            this.overflowAmount = overflowAmount;
            this.effectiveAmount = effectiveAmount;
        }
    }
}
