#nullable enable // autogenerated

using PVZEngine.Armors;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace PVZEngine.Damages
{
    public abstract class DamageInputPart
    {
        public float Amount => Calculator.GetFinalAmount();
        public DamageEffectList Effects { get; private set; }
        public Entity Entity { get; private set; }
        public ILevelSourceReference? Source { get; set; }
        private DamageCalculator Calculator { get; }

        public DamageInputPart(float amount, DamageEffectList effects, Entity entity, ILevelSourceReference? source)
        {
            Calculator = new DamageCalculator(amount);
            Effects = effects;
            Entity = entity;
            Source = source;
        }
        public void Add(float value)
        {
            Calculator.AddOperation(new DamageOperationPlus(value));
        }
        public void Multiply(float value)
        {
            Calculator.AddOperation(new DamageOperationMultiply(value));
        }
        public void SetAmount(float value)
        {
            Calculator.BaseAmount = value;
            Calculator.ClearOperations();
        }
        public float GetOverflowAmount(float targetHP, float actualAmount) => Calculator.GetOverflowAmount(targetHP, actualAmount);
        public bool HasEffect(NamespaceID effect)
        {
            return Effects?.HasEffect(effect) ?? false;
        }
    }
    public class BodyDamageInputPart : DamageInputPart
    {
        public BodyDamageInputPart(DamageInput input) : this(input.Amount, input.Effects, input.Entity, input.Source) { }
        public BodyDamageInputPart(float amount, DamageEffectList effects, Entity entity, ILevelSourceReference? source) 
            : base(amount, effects, entity, source) { }
    }
    public class ArmorDamageInputPart : DamageInputPart
    {
        public ArmorDamageInputPart(DamageInput input ,Armor armor) : this(input.Amount, input.Effects, armor, input.Entity, input.Source) { }
        public ArmorDamageInputPart(float amount, DamageEffectList effects, Armor armor, Entity entity, ILevelSourceReference? source) 
            : base(amount, effects, entity, source) 
        {
            Armor = armor;
        }
        public Armor Armor { get; private set; }
    }
}
