#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using PVZEngine.Callbacks;

namespace PVZEngine
{
    public abstract class Definition
    {
        public Definition(string nsp, string name)
        {
            id = new NamespaceID(nsp, name);
        }
        public virtual bool TryGetProperty<T>(PropertyKey<T> name, out T? value) => propertyDict.TryGetProperty(name, out value);
        public virtual bool TryGetPropertyObject(IPropertyKey name, out object? value) => propertyDict.TryGetPropertyObject(name, out value);
        public virtual T? GetProperty<T>(PropertyKey<T> name) => propertyDict.GetProperty(name);
        public virtual object? GetPropertyObject(IPropertyKey name) => propertyDict.GetPropertyObject(name);
        public void SetProperty<T>(PropertyKey<T> name, T? value) => propertyDict.SetProperty(name, value);
        public void SetPropertyObject(IPropertyKey name, object? value) => propertyDict.SetPropertyObject(name, value);
        public ITrigger[] GetTriggers()
        {
            return triggers.ToArray();
        }
        public void AddTrigger<TArgs, TResult>(CallbackType<TArgs, TResult> callbackID, Action<TArgs, CallbackResult<TResult>> action, int priority = 0)
        {
            triggers.Add(new Trigger<TArgs, TResult>(callbackID, action, priority));
        }
        public void AddTrigger<TArgs>(CallbackType<TArgs> callbackID, Action<TArgs, CallbackResultVoid> action, int priority = 0)
        {
            triggers.Add(new Trigger<TArgs>(callbackID, action, priority));
        }
        public void AddTrigger<TArgs, TResult, TFilter>(CallbackTypeFiltered<TArgs, TResult, TFilter> callbackID, Action<TArgs, CallbackResult<TResult>> action, int priority = 0)
        {
            triggers.Add(new TriggerFiltered<TArgs, TResult, TFilter>(callbackID, action, priority));
        }
        public void AddTrigger<TArgs, TFilter>(CallbackTypeFiltered<TArgs, TFilter> callbackID, Action<TArgs, CallbackResultVoid> action, int priority = 0)
        {
            triggers.Add(new TriggerFiltered<TArgs, TFilter>(callbackID, action, priority));
        }
        public void AddTriggerFiltered<TArgs, TResult, TFilter>(CallbackTypeFiltered<TArgs, TResult, TFilter> callbackID, Action<TArgs, CallbackResult<TResult>> action, TFilter? filter, int priority = 0)
        {
            triggers.Add(new TriggerFiltered<TArgs, TResult, TFilter>(callbackID, action, priority, filter));
        }
        public void AddTriggerFiltered<TArgs, TFilter>(CallbackTypeFiltered<TArgs, TFilter> callbackID, Action<TArgs, CallbackResultVoid> action, TFilter? filter, int priority = 0)
        {
            triggers.Add(new TriggerFiltered<TArgs, TFilter>(callbackID, action, priority, filter));
        }
        public NamespaceID GetID()
        {
            return id;
        }
        public override string ToString()
        {
            return GetID().ToString();
        }
        public abstract string GetDefinitionType();
        public string Namespace => id.SpaceName;
        public string Name => id.Path;
        private NamespaceID id;
        protected PropertyDictionary propertyDict = new PropertyDictionary();
        protected List<ITrigger> triggers = new List<ITrigger>();
    }
}
