#nullable enable // autogenerated

using System.Diagnostics.CodeAnalysis;
using UnityEngine;

namespace PVZEngine.Tools.Unity
{
    public static class UnityHelper
    {
        public static bool Exists([NotNullWhen(true)] this Object? it)
        {
            return it;
        }
    }
}