#nullable enable // autogenerated

using System.Diagnostics.CodeAnalysis;

namespace Tools.Unity
{
    public static class UnityHelper
    {
        public static bool Exists([NotNullWhen(true)] this UnityEngine.Object? it)
        {
            return it;
        }
    }
}